/**
 * German labels for visuals, cards and properties (Power BI Desktop wording).
 * English comes from the schema titles (see labels.ts) with a few overrides.
 */
export const VISUAL_LABELS_DE: Record<string, string> = {
  '*': 'Alle Visuals',
  page: 'Seite',
  barChart: 'Gestapeltes Balkendiagramm',
  clusteredBarChart: 'Gruppiertes Balkendiagramm',
  hundredPercentStackedBarChart: '100 % gestapeltes Balkendiagramm',
  columnChart: 'Gestapeltes Säulendiagramm',
  clusteredColumnChart: 'Gruppiertes Säulendiagramm',
  hundredPercentStackedColumnChart: '100 % gestapeltes Säulendiagramm',
  lineChart: 'Liniendiagramm',
  areaChart: 'Flächendiagramm',
  stackedAreaChart: 'Gestapeltes Flächendiagramm',
  hundredPercentStackedAreaChart: '100 % gestapeltes Flächendiagramm',
  lineClusteredColumnComboChart: 'Linien- und gruppiertes Säulendiagramm',
  lineStackedColumnComboChart: 'Linien- und gestapeltes Säulendiagramm',
  ribbonChart: 'Menübanddiagramm',
  waterfallChart: 'Wasserfalldiagramm',
  funnel: 'Trichter',
  scatterChart: 'Punktdiagramm',
  pieChart: 'Kreisdiagramm',
  donutChart: 'Ringdiagramm',
  treemap: 'Treemap',
  map: 'Karte',
  filledMap: 'Flächenkartogramm',
  shapeMap: 'Formenkarte',
  azureMap: 'Azure Maps',
  gauge: 'Messgerät',
  card: 'Karte (klassisch)',
  cardVisual: 'Karte (neu)',
  multiRowCard: 'Karte mit mehreren Zeilen',
  kpi: 'KPI',
  slicer: 'Datenschnitt',
  advancedSlicerVisual: 'Schaltflächen-Datenschnitt',
  listSlicer: 'Listen-Datenschnitt',
  textSlicer: 'Text-Datenschnitt',
  tableEx: 'Tabelle',
  pivotTable: 'Matrix',
  decompositionTreeVisual: 'Zerlegungsstruktur',
  keyDriversVisual: 'Wichtige Einflussfaktoren',
  scorecard: 'Scorecard',
  actionButton: 'Schaltfläche',
  bookmarkNavigator: 'Lesezeichen-Navigator',
  pageNavigator: 'Seitennavigator',
  textbox: 'Textfeld',
  shape: 'Form',
  image: 'Bild',
};

export const VISUAL_LABELS_EN: Record<string, string> = {
  '*': 'All visuals',
  page: 'Page',
  barChart: 'Stacked bar chart',
  clusteredBarChart: 'Clustered bar chart',
  hundredPercentStackedBarChart: '100% stacked bar chart',
  columnChart: 'Stacked column chart',
  clusteredColumnChart: 'Clustered column chart',
  hundredPercentStackedColumnChart: '100% stacked column chart',
  lineChart: 'Line chart',
  areaChart: 'Area chart',
  stackedAreaChart: 'Stacked area chart',
  hundredPercentStackedAreaChart: '100% stacked area chart',
  lineClusteredColumnComboChart: 'Line and clustered column chart',
  lineStackedColumnComboChart: 'Line and stacked column chart',
  ribbonChart: 'Ribbon chart',
  waterfallChart: 'Waterfall chart',
  funnel: 'Funnel',
  scatterChart: 'Scatter chart',
  pieChart: 'Pie chart',
  donutChart: 'Donut chart',
  treemap: 'Treemap',
  map: 'Map',
  filledMap: 'Filled map',
  shapeMap: 'Shape map',
  azureMap: 'Azure Maps',
  gauge: 'Gauge',
  card: 'Card (classic)',
  cardVisual: 'Card (new)',
  multiRowCard: 'Multi-row card',
  kpi: 'KPI',
  slicer: 'Slicer',
  advancedSlicerVisual: 'Button slicer',
  listSlicer: 'List slicer',
  textSlicer: 'Text slicer',
  tableEx: 'Table',
  pivotTable: 'Matrix',
  decompositionTreeVisual: 'Decomposition tree',
  keyDriversVisual: 'Key influencers',
  scorecard: 'Scorecard',
  actionButton: 'Button',
  bookmarkNavigator: 'Bookmark navigator',
  pageNavigator: 'Page navigator',
  textbox: 'Text box',
  shape: 'Shape',
  image: 'Image',
};

export const CARD_LABELS_DE: Record<string, string> = {
  title: 'Titel', subTitle: 'Untertitel', background: 'Hintergrund', border: 'Visueller Rahmen', dropShadow: 'Schatten',
  visualHeader: 'Kopfzeilensymbole', padding: 'Abstand', spacing: 'Abstände', divider: 'Trennlinie', visualTooltip: 'QuickInfos',
  legend: 'Legende', categoryAxis: 'X-Achse (Kategorie)', valueAxis: 'Y-Achse (Wert)', y2Axis: 'Sekundäre Y-Achse',
  labels: 'Datenbeschriftungen', dataPoint: 'Datenpunkt / Farben', plotArea: 'Zeichenbereich', trend: 'Trendlinie', zoom: 'Zoomschieberegler',
  totals: 'Gesamtbeschriftungen', smallMultiplesLayout: 'Kleine Multiplikatoren', y1AxisReferenceLine: 'Bezugslinie (Y)', xAxisReferenceLine: 'Bezugslinie (X)',
  referenceLine: 'Bezugslinie', ribbonBands: 'Menübänder', layout: 'Layout', lineStyles: 'Linien', markers: 'Markierungen', forecast: 'Prognose',
  seriesLabels: 'Reihenbeschriftungen', bubbles: 'Blasen', fillPoint: 'Punktfüllung', categoryLabels: 'Kategoriebeschriftungen',
  plotAreaShading: 'Schattierung des Zeichenbereichs', ratioLine: 'Verhältnislinie', colorByCategory: 'Farbe nach Kategorie',
  sentimentColors: 'Stimmungsfarben', breakdown: 'Aufschlüsselung', slices: 'Segmente', percentBarLabel: 'Konvertierungsrate',
  axis: 'Messgerätachse', calloutValue: 'Legendenwert', target: 'Zielbeschriftung', wordWrap: 'Zeilenumbruch', value: 'Legendenwerte',
  label: 'Beschriftung', accentBar: 'Akzentleiste', referenceLabelValue: 'Referenzbeschriftung – Wert', referenceLabelTitle: 'Referenzbeschriftung – Titel',
  fillCustom: 'Füllung', outline: 'Rahmen', shapeCustomRectangle: 'Form', grid: 'Raster', card: 'Karte', cardTitle: 'Kartentitel', dataLabels: 'Datenbeschriftungen',
  indicator: 'Legendenwert', trendline: 'Trendachse', goals: 'Ziel', status: 'Status', lastDate: 'Datum',
  header: 'Kopfzeile des Datenschnitts', items: 'Werte', data: 'Datenschnitteinstellungen', selection: 'Auswahl', slider: 'Schieberegler', searchBox: 'Suchfeld',
  date: 'Datumseingabe', numericInputStyle: 'Numerische Eingabe', selectionIcon: 'Auswahlsymbol',
  columnHeaders: 'Spaltenüberschriften', values: 'Werte', total: 'Gesamt', columnFormatting: 'Bestimmte Spalte', rowHeaders: 'Zeilenüberschriften',
  subTotals: 'Zwischensummen', columnTotal: 'Spaltensumme', rowTotal: 'Zeilensumme',
  levelHeader: 'Ebenenkopfzeile', tree: 'Struktur', dataBars: 'Datenbalken', keyInfluencersVisual: 'Einflussfaktoren', keyDriversDrillVisual: 'Detailansicht',
  scorecard: 'Scorecard', detailsPane: 'Detailbereich',
  text: 'Text', fill: 'Füllung', shadow: 'Schatten', glow: 'Leuchten', icon: 'Symbol', shape: 'Form', rotation: 'Drehung', pages: 'Seiten',
  imageScaling: 'Skalierung', mapStyles: 'Kartenstil', mapControls: 'Kartensteuerelemente', stroke: 'Umrandung', defaultColors: 'Standardfarbe',
  bubbleLayer: 'Blasenebene', filledMap: 'Flächenkartogramm-Ebene', heatMapLayer: 'Wärmebildebene', barChart: 'Balkendiagramm-Ebene',
  inputText: 'Eingabetext', inputTextBox: 'Eingabefeld', applyButton: 'Schaltfläche „Anwenden“', slicerSettings: 'Datenschnitteinstellungen',
  outspace: 'Hintergrundbild (Wallpaper)', outspacePane: 'Filterbereich', filterCard: 'Filterkarten', pageSize: 'Canvas-Einstellungen', displayArea: 'Anzeigebereich',
};

export const CARD_LABELS_EN_OVERRIDE: Record<string, string> = {
  background: 'Background', border: 'Visual border', dropShadow: 'Shadow', visualHeader: 'Header icons', padding: 'Padding',
  categoryAxis: 'X-axis (category)', valueAxis: 'Y-axis (value)', y2Axis: 'Secondary Y-axis', labels: 'Data labels', dataPoint: 'Data point / colors',
  outspace: 'Wallpaper', outspacePane: 'Filter pane', filterCard: 'Filter cards', pageSize: 'Canvas settings', displayArea: 'Display area',
  header: 'Slicer header', items: 'Values', value: 'Callout values', indicator: 'Callout value', calloutValue: 'Callout value', slices: 'Slices',
};

export const PROP_LABELS_DE: Record<string, string> = {
  show: 'Anzeigen', text: 'Text', titleText: 'Titeltext', fontFamily: 'Schriftart', fontSize: 'Textgröße', textSize: 'Textgröße', bold: 'Fett', italic: 'Kursiv', underline: 'Unterstrichen',
  fontColor: 'Schriftfarbe', color: 'Farbe', labelColor: 'Farbe', alignment: 'Ausrichtung', horizontalAlignment: 'Horizontale Ausrichtung', verticalAlignment: 'Vertikale Ausrichtung',
  titleWrap: 'Zeilenumbruch', heading: 'Überschriftenebene', background: 'Hintergrundfarbe', transparency: 'Transparenz (%)', radius: 'Abgerundete Ecken (px)', width: 'Breite (px)',
  weight: 'Breite (px)', preset: 'Position', position: 'Position', shadowBlur: 'Weichzeichnen', shadowDistance: 'Abstand', shadowSpread: 'Größe', angle: 'Winkel',
  foreground: 'Symbolfarbe', top: 'Oben (px)', bottom: 'Unten (px)', left: 'Links (px)', right: 'Rechts (px)', customizeSpacing: 'Abstände anpassen',
  spaceBelowTitle: 'Unter Titel', spaceBelowSubTitle: 'Unter Untertitel', spaceBelowTitleArea: 'Unter Titelbereich', verticalSpacing: 'Vertikaler Abstand',
  style: 'Stil', ignorePadding: 'Abstand ignorieren', type: 'Typ', titleFontColor: 'Titelfarbe', valueFontColor: 'Wertfarbe',
  showTitle: 'Titel anzeigen', showGradientLegend: 'Farbverlaufslegende', axisType: 'Typ', axisStyle: 'Titelstil', showAxisTitle: 'Achsentitel anzeigen',
  titleColor: 'Titelfarbe', titleFontFamily: 'Titel-Schriftart', titleFontSize: 'Titel-Textgröße', titleBold: 'Titel fett', titleItalic: 'Titel kursiv', titleUnderline: 'Titel unterstrichen',
  gridlineShow: 'Gitternetzlinien', gridlineColor: 'Gitternetzfarbe', gridlineStyle: 'Gitternetzstil', gridlineThickness: 'Gitternetzbreite', gridlineTransparency: 'Gitternetz-Transparenz',
  labelDisplayUnits: 'Anzeigeeinheiten', labelPrecision: 'Dezimalstellen', invertAxis: 'Bereich umkehren', concatenateLabels: 'Beschriftungen verketten', innerPadding: 'Innenabstand (%)',
  switchAxisPosition: 'Achsenposition wechseln', preferredCategoryWidth: 'Kategoriebreite', maxMarginFactor: 'Max. Randfaktor (%)', logAxisScale: 'Logarithmische Skala',
  scaleToFit: 'An Größe anpassen', sharedAxis: 'Gemeinsame Y-Achse', labelPosition: 'Position', labelOrientation: 'Ausrichtung', labelDensity: 'Dichte (%)', labelOverflow: 'Überlauftext',
  labelContentLayout: 'Layout', showAll: 'Alle anzeigen', showSeries: 'Reihenname anzeigen', showBlankAs: 'Leer anzeigen als', enableBackground: 'Hintergrund', backgroundColor: 'Hintergrundfarbe',
  backgroundTransparency: 'Hintergrund-Transparenz', optimizeLabelDisplay: 'Anzeige optimieren', labelContainerMaxWidth: 'Max. Breite', enableTitleDataLabel: 'Titel', enableDetailDataLabel: 'Detail',
  detailContentType: 'Detailinhalt', detailColor: 'Detailfarbe', detailFontFamily: 'Detail-Schriftart', detailFontSize: 'Detail-Textgröße', detailBold: 'Detail fett', detailItalic: 'Detail kursiv',
  defaultColor: 'Standardfarbe', fillTransparency: 'Transparenz (%)', borderShow: 'Rahmen', borderColor: 'Rahmenfarbe', borderSize: 'Rahmenbreite', borderTransparency: 'Rahmen-Transparenz',
  borderColorMatchFill: 'Rahmen = Füllfarbe', borderOutlineOnly: 'Nur Umriss', showAllDataPoints: 'Alle anzeigen', lineColor: 'Linienfarbe', combineSeries: 'Reihen kombinieren',
  useHighlightValues: 'Hervorgehobene Werte', displayName: 'Name', showOnCategoryAxis: 'Auf X-Achse', showOnValueAxis: 'Auf Y-Achse', showLabels: 'Beschriftungen', showTooltip: 'QuickInfo',
  showPositiveAndNegative: 'Positiv und negativ', layoutType: 'Layout', rowCount: 'Zeilen', columnCount: 'Spalten', gridLineShow: 'Gitternetzlinien', gridLineType: 'Gitternetztyp',
  gridLineColor: 'Gitternetzfarbe', gridLineStyle: 'Gitternetzstil', gridLineWidth: 'Gitternetzbreite', gridLineTransparency: 'Gitternetz-Transparenz', gridPadding: 'Rasterabstand',
  rowPaddingInner: 'Zeilenabstand innen', rowPaddingOuter: 'Zeilenabstand außen', columnPaddingInner: 'Spaltenabstand innen', columnPaddingOuter: 'Spaltenabstand außen',
  value: 'Wert', dataLabelShow: 'Datenbeschriftung', dataLabelColor: 'Beschriftungsfarbe', dataLabelText: 'Beschriftungstext', dataLabelHorizontalPosition: 'Horizontale Position',
  dataLabelVerticalPosition: 'Vertikale Position', dataLabelDisplayUnits: 'Anzeigeeinheiten', dataLabelDecimalPoints: 'Dezimalstellen', shadeShow: 'Schattierung', shadeColor: 'Schattierungsfarbe',
  shadeRegion: 'Schattierter Bereich', shadeTransparency: 'Schattierungs-Transparenz', fillColor: 'Füllfarbe', fillMatchColor: 'Reihenfarbe verwenden', seriesOrderReversed: 'Reihenfolge umkehren',
  seriesOrderSorted: 'Reihen sortieren', stackedGapExplodes: 'Lücke bei Explosion', stackedGapSize: 'Lückengröße', ribbonGapSize: 'Lücke zwischen Bändern',
  lineChartType: 'Linientyp', interpolationSmooth: 'Glättung', interpolationStep: 'Stufenposition', lineStyle: 'Linienstil', strokeWidth: 'Linienbreite', strokeTransparency: 'Linien-Transparenz',
  strokeLineJoin: 'Verbindungstyp', strokeDashCap: 'Strichende', showMarker: 'Markierungen', markerShape: 'Form', markerSize: 'Größe', markerColor: 'Markierungsfarbe', areaShow: 'Schattierter Bereich',
  areaColor: 'Flächenfarbe', areaMatchStrokeColor: 'Fläche = Linienfarbe', segmentGradient: 'Verlauf', borderWidth: 'Rahmenbreite', rotation: 'Drehung', interpolation: 'Interpolation',
  bandAreaShow: 'Konfidenzband', bandAreaColor: 'Bandfarbe', bandAreaMatchColor: 'Band = Linienfarbe', bandAreaTransparency: 'Band-Transparenz', bandLineShow: 'Bandlinie', bandLineColor: 'Bandlinienfarbe',
  bandLinePattern: 'Bandlinienstil', bandLineWidth: 'Bandlinienbreite', seriesPosition: 'Position', seriesColor: 'Farbe', seriesFontFamily: 'Schriftart', seriesMaximumWidth: 'Max. Breite (%)',
  seriesWordWrap: 'Zeilenumbruch', secAxisStyle: 'Titelstil', secLabelColor: 'Farbe', secFontFamily: 'Schriftart', secFontSize: 'Textgröße', secBold: 'Fett', secItalic: 'Kursiv', secUnderline: 'Unterstrichen',
  secShowAxisTitle: 'Achsentitel anzeigen', secTitleText: 'Titeltext', secTitleColor: 'Titelfarbe', secTitleFontFamily: 'Titel-Schriftart', secTitleFontSize: 'Titel-Textgröße', secTitleBold: 'Titel fett',
  secLabelDisplayUnits: 'Anzeigeeinheiten', secLabelPrecision: 'Dezimalstellen', secLogAxisScale: 'Logarithmische Skala', bubbleSize: 'Größe', markerRangeType: 'Bereich',
  upperShadingColor: 'Obere Schattierung', lowerShadingColor: 'Untere Schattierung', increaseFill: 'Zunahme', decreaseFill: 'Abnahme', totalFill: 'Gesamt', otherFill: 'Sonstige',
  maxBreakdowns: 'Max. Aufschlüsselungen', innerRadiusRatio: 'Innerer Radius (%)', startAngle: 'Startwinkel', labelStyle: 'Beschriftungsinhalt', percentageLabelPrecision: 'Prozent-Dezimalstellen',
  overflow: 'Überlauftext', funnelLabelStyle: 'Beschriftungsinhalt', min: 'Minimum', max: 'Maximum', textWrap: 'Zeilenumbruch', matchValueAlignment: 'An Wert ausrichten',
  valueFontFamily: 'Wert-Schriftart', valueFontSize: 'Wert-Textgröße', valueBold: 'Wert fett', valueItalic: 'Wert kursiv', titleContentType: 'Titelinhalt',
  tileShape: 'Form', rectangleRoundedCurve: 'Abgerundete Ecken (px)', roundEdge: 'Abgerundete Ecken (px)', linecapType: 'Linienende', barShow: 'Balken', barColor: 'Balkenfarbe', barWeight: 'Balkenbreite',
  cardBackground: 'Kartenhintergrund', cardPadding: 'Innenabstand', outlineColor: 'Rahmenfarbe', outlineStyle: 'Rahmenstil', outlineWeight: 'Rahmenbreite', iconSize: 'Symbolgröße',
  indicatorDisplayUnits: 'Anzeigeeinheiten', indicatorPrecision: 'Dezimalstellen', showIcon: 'Symbol anzeigen', showGoal: 'Ziel anzeigen', goalText: 'Zieltext', goalFontColor: 'Zielfarbe',
  goalFontFamily: 'Ziel-Schriftart', showDistance: 'Abstand anzeigen', distanceLabel: 'Abstandsbeschriftung', distanceFontColor: 'Abstandsfarbe', distanceFontFamily: 'Abstands-Schriftart',
  direction: 'Richtung', goodColor: 'Gut', neutralColor: 'Neutral', badColor: 'Schlecht', lastDateFontColor: 'Datumsfarbe', lastDateFontFamily: 'Datums-Schriftart',
  showRestatement: 'Auswahl im Titel', steppedLayoutIndentation: 'Einzug (px)', expandCollapseToggleType: 'Erweitern/Reduzieren-Symbol', mode: 'Stil', singleSelect: 'Einzelauswahl',
  strictSingleSelect: 'Strikte Einzelauswahl', selectAllCheckboxEnabled: 'Option „Alle auswählen“', restrictToLeafNodes: 'Nur Blattknoten', handleFillColor: 'Griff-Füllung', handleBorderColor: 'Griff-Rahmen',
  secondaryLineColor: 'Hintergrundlinie', hideDatePickerButton: 'Datumsauswahl ausblenden', size: 'Größe', spacing: 'Abstand', overlayPosition: 'Überlagerungsposition',
  backColor: 'Hintergrundfarbe', backColorPrimary: 'Hintergrund (ungerade)', backColorSecondary: 'Hintergrund (gerade)', fontColorPrimary: 'Schrift (ungerade)', fontColorSecondary: 'Schrift (gerade)',
  wordWrap: 'Zeilenumbruch', autoSizeColumnWidth: 'Automatische Spaltenbreite', urlIcon: 'URL-Symbol', totals: 'Gesamtergebnisse', label: 'Beschriftung', gridVertical: 'Vertikale Gitternetzlinien',
  gridVerticalColor: 'Vertikale Farbe', gridVerticalWeight: 'Vertikale Breite', gridHorizontal: 'Horizontale Gitternetzlinien', gridHorizontalColor: 'Horizontale Farbe', gridHorizontalWeight: 'Horizontale Breite',
  rowPadding: 'Zeilenabstand', imageHeight: 'Bildhöhe', styleHeader: 'Auf Kopfzeile anwenden', styleValues: 'Auf Werte anwenden', styleTotal: 'Auf Gesamt anwenden', titleAlignment: 'Titelausrichtung',
  bandedRowHeaders: 'Zeilenüberschriften abwechselnd', valuesOnRow: 'Werte in Zeilen', stepped: 'Gestuftes Layout', showExpandCollapseButtons: 'Erweitern/Reduzieren-Symbole',
  expandCollapseButtonsColor: 'Symbolfarbe', expandCollapseButtonsSize: 'Symbolgröße', repeatRowHeaders: 'Zeilenüberschriften wiederholen', rowSubtotals: 'Zeilenzwischensummen',
  rowSubtotalsLabel: 'Beschriftung Zeilen', rowSubtotalsPosition: 'Position', columnSubtotals: 'Spaltenzwischensummen', columnSubtotalsLabel: 'Beschriftung Spalten', perRowLevel: 'Pro Zeilenebene',
  perColumnLevel: 'Pro Spaltenebene', applyToHeaders: 'Auf Beschriftungen anwenden', showSubtitles: 'Untertitel anzeigen', levelHeaderBackgroundColor: 'Hintergrund', levelTitleFontColor: 'Titelfarbe',
  levelTitleFontFamily: 'Titel-Schriftart', levelTitleFontSize: 'Titel-Textgröße', levelTitleBold: 'Titel fett', levelTitleItalic: 'Titel kursiv', levelTitleUnderline: 'Titel unterstrichen',
  levelSubtitleFontColor: 'Untertitelfarbe', levelSubtitleFontFamily: 'Untertitel-Schriftart', levelSubtitleFontSize: 'Untertitel-Textgröße', levelSubtitleBold: 'Untertitel fett',
  accentColor: 'Akzentfarbe', connectorDefaultColor: 'Verbindungsfarbe', connectorType: 'Verbindungstyp', barsPerLevel: 'Balken pro Ebene', density: 'Dichte', responsiveLayout: 'Responsives Layout',
  dataBarColor: 'Balkenfarbe', dataBarBackgroundColor: 'Balkenhintergrund', positiveBarColor: 'Positiv', negativeBarColor: 'Negativ', dataBarWidthPercent: 'Breite (%)', dataBarScalingType: 'Skalierung',
  categoryLabelFontColor: 'Farbe', categoryLabelFontFamily: 'Schriftart', categoryLabelFontSize: 'Textgröße', categoryLabelBold: 'Fett', categoryLabelItalic: 'Kursiv', categoryLabelUnderline: 'Unterstrichen',
  dataLabelFontColor: 'Farbe', dataLabelFontFamily: 'Schriftart', dataLabelFontSize: 'Textgröße', dataLabelBold: 'Fett', dataLabelItalic: 'Kursiv', dataLabelUnderline: 'Unterstrichen',
  dataLabelPrecision: 'Dezimalstellen', canvasColor: 'Canvasfarbe', primaryColor: 'Primärfarbe', primaryFontColor: 'Primäre Schriftfarbe',
  secondaryColor: 'Sekundärfarbe', secondaryFontColor: 'Sekundäre Schriftfarbe', referenceLineColor: 'Bezugslinienfarbe', displayMode: 'Anzeigemodus', foregroundColor: 'Vordergrundfarbe',
  tableBackgroundColor: 'Tabellenhintergrund', showCommandBar: 'Befehlsleiste', showCards: 'Karten anzeigen', showToolbar: 'Symbolleiste', cardBackgroundColor: 'Kartenhintergrund',
  cardForegroundColor: 'Kartenvordergrund', chartBackgroundColor: 'Diagrammhintergrund', chartForegroundColor: 'Diagrammvordergrund', topMargin: 'Rand oben', bottomMargin: 'Rand unten',
  leftMargin: 'Rand links', rightMargin: 'Rand rechts', shadowPositionPreset: 'Position', shapeType: 'Symboltyp', placement: 'Platzierung', lineWeight: 'Linienbreite', lineTransparency: 'Linien-Transparenz',
  shapeAngle: 'Formdrehung', textAngle: 'Textdrehung', showHiddenPages: 'Ausgeblendete Seiten', showTooltipPages: 'QuickInfo-Seiten', imageScalingType: 'Skalierung', mapTheme: 'Kartendesign',
  autoZoom: 'Automatischer Zoom', showZoomButtons: 'Zoomschaltflächen', showLassoButton: 'Lasso-Schaltfläche', strokeColor: 'Umrandungsfarbe', defaultShow: 'Standard anzeigen', borderThickness: 'Rahmenbreite',
  bubbleRadius: 'Blasengröße', minBubbleRadius: 'Minimale Größe', maxRadius: 'Maximale Größe', bubbleStrokeWidth: 'Umrandungsbreite', matchFillColor: 'Umrandung = Füllfarbe', autoStrokeColor: 'Automatische Umrandung',
  clusteringEnabled: 'Clustering', clusteredBubbleFillColor: 'Cluster-Füllung', clusteredBubbleStrokeColor: 'Cluster-Umrandung', heatMapColorLow: 'Niedrig', heatMapColorCenter: 'Mitte', heatMapColorHigh: 'Hoch',
  heatMapRadius: 'Radius', heatMapIntensity: 'Intensität', barHeight: 'Balkenhöhe', thickness: 'Dicke', barShape: 'Balkenform', defaultStyle: 'Kartenstil', showNavigationControls: 'Navigationssteuerung',
  showStylePicker: 'Stilauswahl', showSelectionControl: 'Auswahlsteuerung', projectionEnum: 'Projektion', manualZoom: 'Manueller Zoom', selectionZoom: 'Auswahlzoom', pageSizeTypes: 'Typ',
  pageSizeWidth: 'Breite (px)', pageSizeHeight: 'Höhe (px)', titleSize: 'Titelgröße', headerSize: 'Überschriftengröße', searchTextSize: 'Suchtextgröße', inputBoxColor: 'Eingabefeldfarbe',
  checkboxAndApplyColor: 'Kontrollkästchen und Schaltfläche', border: 'Rahmen', borderStyle: 'Rahmenstil', backgroundShow: 'Hintergrund', backgroundFillColor: 'Hintergrundfarbe',
  cellPadding: 'Zellenabstand', maxTiles: 'Max. Kacheln', orientation: 'Ausrichtung', pillCornerRadius: 'Abgerundete Ecken', showByDefault: 'Standardmäßig anzeigen',
  // variant cards (card visual, button/list slicer), matrix grid, combo secondary axis
  dividerColor: 'Farbe', dividerLineStyle: 'Stil', dividerWidth: 'Breite (px)', dividerTransparency: 'Transparenz (%)', dividerIgnorePadding: 'Abstand ignorieren',
  paddingSelection: 'Abstandsvorgabe', wrapContent: 'Inhalt umbrechen',
  imageWidth: 'Bildbreite', target: 'Ziel', fill: 'Füllfarbe', padding: 'Innenabstand (px)', outerPadding: 'Außenabstand (px)', tilingMethod: 'Kachelmethode', secShow: 'Sekundäre Achse anzeigen', secTitleItalic: 'Titel kursiv', secTitleUnderline: 'Titel unterstrichen', alignZeros: 'Nullen ausrichten',
  // text slicer
  backShow: 'Hintergrund', backTransparency: 'Hintergrund-Transparenz',
  placeholder: 'Platzhaltertext', fontTransparency: 'Text-Transparenz', dismissColor: 'Löschsymbol-Farbe', dismissSize: 'Löschsymbol-Größe', dismissSpacing: 'Löschsymbol-Abstand', dismissTransparency: 'Löschsymbol-Transparenz',
  paddingTop: 'Abstand oben', paddingBottom: 'Abstand unten', paddingLeft: 'Abstand links', paddingRight: 'Abstand rechts', accentBarShow: 'Akzentleiste', accentBarColor: 'Akzentleistenfarbe',
  accentBarPosition: 'Akzentleistenposition', accentBarWidth: 'Akzentleistenbreite', accentBarTransparency: 'Akzentleisten-Transparenz', iconColor: 'Symbolfarbe', iconTransparency: 'Symbol-Transparenz', multiselect: 'Mehrfachauswahl',
};

/** `$id` state labels (Power BI "Anwenden auf → Zustand"). */
export const STATE_LABELS_DE: Record<string, string> = {
  default: 'Standard', hover: 'Beim Daraufzeigen', selected: 'Beim Drücken', disabled: 'Deaktiviert',
  Applied: 'Angewendet', Available: 'Verfügbar', Row: 'Zeilen', Column: 'Spalten',
  // button / list slicer (actionStates): interaction and selection states
  'interaction:hover': 'Beim Daraufzeigen', 'interaction:press': 'Beim Drücken', press: 'Beim Drücken (veraltet)', selection: 'Ausgewählt (veraltet)',
  'selection:selected': 'Ausgewählt', 'selection:unselected': 'Nicht ausgewählt', 'expansion:expanded': 'Erweitert', 'expansion:collapsed': 'Reduziert', 'series:selectall': '„Alle auswählen“',
};
export const STATE_LABELS_EN: Record<string, string> = {
  default: 'Default', hover: 'On hover', selected: 'On press', disabled: 'Disabled',
  Applied: 'Applied', Available: 'Available', Row: 'Rows', Column: 'Columns',
  'interaction:hover': 'On hover', 'interaction:press': 'On press', press: 'On press (legacy)', selection: 'Selected (legacy)',
  'selection:selected': 'Selected', 'selection:unselected': 'Unselected', 'expansion:expanded': 'Expanded', 'expansion:collapsed': 'Collapsed', 'series:selectall': '"Select all"',
};

/** German labels for enum option values (fallback: schema title). */
export const ENUM_LABELS_DE: Record<string, string> = {
  left: 'Links', center: 'Mitte', right: 'Rechts', top: 'Oben', middle: 'Mitte', bottom: 'Unten',
  Top: 'Oben links', TopCenter: 'Oben zentriert', TopRight: 'Oben rechts', Left: 'Oben links gestapelt', Right: 'Oben rechts gestapelt', LeftCenter: 'Mitte links', RightCenter: 'Mitte rechts',
  Bottom: 'Unten links', BottomCenter: 'Unten zentriert', BottomRight: 'Unten rechts',
  solid: 'Durchgezogen', dashed: 'Gestrichelt', dotted: 'Gepunktet', custom: 'Benutzerdefiniert',
  Scalar: 'Fortlaufend', Categorical: 'Kategorisch', showTitleOnly: 'Nur Titel anzeigen', showUnitOnly: 'Nur Einheit anzeigen', showBoth: 'Beides anzeigen',
  Auto: 'Automatisch', InsideEnd: 'Innen, Ende', OutsideEnd: 'Außen, Ende', InsideCenter: 'Innen, Mitte', InsideBase: 'Innen, Basis', Above: 'Oberhalb', Under: 'Unterhalb',
  Category: 'Kategorie', Data: 'Datenwert', 'Percent of total': 'Prozent des Gesamtwerts', Both: 'Kategorie, Datenwert', 'Category, percent of total': 'Kategorie, Prozent', 'Data value, percent of total': 'Datenwert, Prozent',
  'Category, data value, percent of total': 'Kategorie, Datenwert, Prozent', 'Percent of first': 'Prozent vom ersten', 'Percent of previous': 'Prozent vom vorherigen', 'Data, percent of first': 'Datenwert, Prozent vom ersten', 'Data, percent of previous': 'Datenwert, Prozent vom vorherigen',
  outside: 'Außen', inside: 'Innen', preferOutside: 'Bevorzugt außen', preferInside: 'Bevorzugt innen', auto: 'Automatisch', on: 'Ein', off: 'Aus',
  linear: 'Gerade', smooth: 'Geglättet', step: 'Gestuft', circle: 'Kreis', square: 'Quadrat', diamond: 'Raute', triangle: 'Dreieck', x: 'X', plus: 'Plus', shortDash: 'Kurzer Strich', longDash: 'Langer Strich',
  'Fill only': 'Nur Füllung', 'Border only': 'Nur Rahmen', Normal: 'Normal', Fit: 'Anpassen', Fill: 'Ausfüllen', Widescreen: '16:9', Standard: '4:3', Letter: 'Letter', Tooltip: 'QuickInfo', Custom: 'Benutzerdefiniert',
  Cards: 'Karten', Table: 'Tabelle', belowValue: 'Unter dem Wert', aboveValue: 'Über dem Wert', VerticalList: 'Vertikale Liste', HorizontalList: 'Horizontale Liste', Dropdown: 'Dropdown', Between: 'Zwischen', Before: 'Vor', After: 'Nach', Basic: 'Liste', Relative: 'Relatives Datum', Single: 'Einzelwert', RelativeTime: 'Relative Zeit',
  'High is good': 'Hoch ist gut', 'Low is good': 'Niedrig ist gut', Positive: 'Positiv', Negative: 'Negativ', Value: 'Wert', Percent: 'Prozent', 'Value, percent': 'Wert, Prozent', Name: 'Name', ValueAndName: 'Wert und Name',
  back: 'Hinten', front: 'Vorn', before: 'Davor', after: 'Danach', none: 'Keine', Outer: 'Außen', Inner: 'Innen', Default: 'Standard', Canvas: 'Canvas',
  None: 'Keine', Thousands: 'Tausend', Millions: 'Millionen', Billions: 'Milliarden', Trillions: 'Billionen',
  Wide: 'Weit', Narrow: 'Eng',
  rectangle: 'Rechteck', rectangleRounded: 'Abgerundetes Rechteck', oval: 'Oval', pill: 'Pille', pentagon: 'Fünfeck', hexagon: 'Sechseck', octagon: 'Achteck', arrow: 'Pfeil', arrowChevron: 'Chevron', heart: 'Herz', line: 'Linie',
  parallelogram: 'Parallelogramm', trapezoid: 'Trapez', triangleIsoc: 'Gleichschenkliges Dreieck', triangleRight: 'Rechtwinkliges Dreieck', road: 'Straße', aerial: 'Luftbild', grayscale: 'Graustufen', canvasDark: 'Dunkel', canvasLight: 'Hell',
  tile: 'Kachel', list: 'Liste', curve: 'Kurve', round: 'Abgerundet', dense: 'Dicht', default: 'Standard', sparse: 'Locker', Heading2: 'Überschrift 2', Heading3: 'Überschrift 3', Heading4: 'Überschrift 4', Heading5: 'Überschrift 5', Heading6: 'Überschrift 6',
  stableSquarified: 'Quadriert', binary: 'Binär', alternating: 'Abwechselnd', MultiLine: 'Mehrzeilig', SingleLine: 'Einzeilig', 'Series name': 'Reihenname', all: 'Alle', inner: 'Innen', innerHorizontal: 'Innen horizontal', innerVertical: 'Innen vertikal',
};

/** German labels for the theme colour keys. */
export const COLOR_LABELS_DE: Record<string, string> = {
  foreground: 'Vordergrund (Text)', background: 'Hintergrund', firstLevelElements: 'Elemente der ersten Ebene', secondLevelElements: 'Elemente der zweiten Ebene',
  thirdLevelElements: 'Elemente der dritten Ebene', fourthLevelElements: 'Elemente der vierten Ebene', secondaryBackground: 'Sekundärer Hintergrund', tableAccent: 'Tabellenakzent',
  good: 'Gut', neutral: 'Neutral', bad: 'Schlecht', maximum: 'Maximum', center: 'Mitte', minimum: 'Minimum', null: 'Null',
  accent: 'Akzent', hyperlink: 'Link', visitedHyperlink: 'Besuchter Link', shapeStroke: 'Formkontur', disabledText: 'Deaktivierter Text', mapPushpin: 'Kartenmarkierung',
  foregroundLight: 'Vordergrund hell', foregroundDark: 'Vordergrund dunkel', foregroundNeutralLight: 'Neutral hell', foregroundNeutralDark: 'Neutral dunkel', foregroundNeutralSecondary: 'Neutral sekundär',
  foregroundNeutralSecondaryAlt: 'Neutral sekundär (Alt)', foregroundNeutralSecondaryAlt2: 'Neutral sekundär (Alt 2)', foregroundNeutralTertiary: 'Neutral tertiär', foregroundNeutralTertiaryAlt: 'Neutral tertiär (Alt)',
  foregroundSelected: 'Ausgewählt', foregroundButton: 'Schaltfläche', backgroundLight: 'Hintergrund hell', backgroundNeutral: 'Hintergrund neutral', backgroundDark: 'Hintergrund dunkel',
};

export const COLOR_LABELS_EN: Record<string, string> = {
  foreground: 'Foreground (text)', background: 'Background', firstLevelElements: 'First-level elements', secondLevelElements: 'Second-level elements',
  thirdLevelElements: 'Third-level elements', fourthLevelElements: 'Fourth-level elements', secondaryBackground: 'Secondary background', tableAccent: 'Table accent',
  good: 'Good', neutral: 'Neutral', bad: 'Bad', maximum: 'Maximum', center: 'Center', minimum: 'Minimum', null: 'Null',
  accent: 'Accent', hyperlink: 'Hyperlink', visitedHyperlink: 'Visited hyperlink', shapeStroke: 'Shape stroke', disabledText: 'Disabled text', mapPushpin: 'Map pushpin',
};

export const TEXT_CLASS_LABELS_DE: Record<string, string> = {
  label: 'Allgemein (label)', title: 'Titel (title)', callout: 'Karten und KPIs (callout)', header: 'Registerkartenüberschriften (header)',
  largeTitle: 'Großer Titel', dataTitle: 'Datentitel', largeLabel: 'Große Beschriftung', boldLabel: 'Fette Beschriftung', semiboldLabel: 'Halbfette Beschriftung',
  smallLabel: 'Kleine Beschriftung', lightLabel: 'Helle Beschriftung', largeLightLabel: 'Große helle Beschriftung', smallLightLabel: 'Kleine helle Beschriftung', smallDataLabel: 'Kleine Datenbeschriftung',
};
export const TEXT_CLASS_LABELS_EN: Record<string, string> = {
  label: 'General (label)', title: 'Title (title)', callout: 'Cards and KPIs (callout)', header: 'Tab headers (header)',
  largeTitle: 'Large title', dataTitle: 'Data title', largeLabel: 'Large label', boldLabel: 'Bold label', semiboldLabel: 'Semibold label',
  smallLabel: 'Small label', lightLabel: 'Light label', largeLightLabel: 'Large light label', smallLightLabel: 'Small light label', smallDataLabel: 'Small data label',
};
