export const FONTS = [
  'Aptos',
  'Aptos Display',
  'Arial',
  'Calibri',
  'Cambria',
  'Century Gothic',
  'Consolas',
  'Courier New',
  'DIN',
  'Franklin Gothic Medium',
  'Garamond',
  'Georgia',
  'Impact',
  'Lucida Sans Unicode',
  'Palatino Linotype',
  'Segoe UI',
  'Segoe UI Light',
  'Segoe UI Semibold',
  'Tahoma',
  'Times New Roman',
  'Trebuchet MS',
  'Verdana',
];

export const ENUMS = {
  position: ['Top', 'Bottom', 'Left', 'Right', 'TopLeft', 'TopRight', 'BottomLeft', 'BottomRight'],
  alignment: ['left', 'center', 'right'],
  verticalAlignment: ['top', 'middle', 'bottom'],
  fontFamily: FONTS,
  outline: ['None', 'Frame', 'Top', 'Bottom', 'Left', 'Right', 'TopBottom'],
  imageScalingType: ['Fit', 'Fill', 'Normal'],
  labelStyle: ['category', 'data', 'both', 'percent', 'percentOfTotal'],
};

export const VALIDATION = {
  fontSize:              { min: 6,   max: 96,  step: 1 },
  transparency:          { min: 0,   max: 100, step: 1 },
  strokeWidth:           { min: 0,   max: 20,  step: 1 },
  weight:                { min: 1,   max: 10,  step: 1 },
  outlineWeight:         { min: 1,   max: 10,  step: 1 },
  gridHorizontalWeight:  { min: 1,   max: 10,  step: 1 },
  markerSize:            { min: 1,   max: 20,  step: 1 },
  thickness:             { min: 1,   max: 10,  step: 1 },
  arcAngle:              { min: 60,  max: 270, step: 1 },
  startAngle:            { min: -180, max: 0,  step: 1 },
  innerRadiusRatio:      { min: 0,   max: 100, step: 1 },
  minBubbleSize:         { min: 1,   max: 100, step: 1 },
  maxBubbleSize:         { min: 1,   max: 200, step: 1 },
  rowPadding:            { min: 0,   max: 20,  step: 1 },
  steppedLayoutIndentation: { min: 0, max: 100, step: 1 },
  labelDisplayUnits:     { min: 0,   max: 4,   step: 1 },
};

export const PBI_PAGE_SIZES = {
  'Custom':                    null,
  '16:9 (HD 1280×720)':       [1280, 720],
  '16:9 (Full HD 1920×1080)': [1920, 1080],
  '16:9 (4K 3840×2160)':      [3840, 2160],
  '4:3 (960×720)':            [960, 720],
  'Letter (816×1056)':        [816, 1056],
  'A4 (793×1122)':            [793, 1122],
  'Mobile Portrait (320×568)': [320, 568],
  'Square (700×700)':         [700, 700],
};
