export const THEME_INITIAL = {
  name: 'Customer360 Theme',
  textClasses: {
    title:   { fontFace: 'Segoe UI', fontSize: 14, fontBold: true,  fontColor: '#0F4C81' },
    header:  { fontFace: 'Segoe UI', fontSize: 12, fontBold: true,  fontColor: '#374649' },
    label:   { fontFace: 'Segoe UI', fontSize: 10, fontBold: false, fontColor: '#666666' },
    callout: { fontFace: 'Segoe UI', fontSize: 45, fontBold: false, fontColor: '#374649' },
  },
  dataColors: ['#0F4C81', '#1F8AC0', '#3BBFCE', '#70C1B3', '#F4A261', '#E76F51', '#264653', '#2A9D8F'],
  background: '#FFFFFF',
  foreground: '#0F4C81',
  tableAccent: '#1F8AC0',
  good: '#1AAB40',
  neutral: '#D9B300',
  bad: '#D63554',
  maximum: '#1F8AC0',
  center: '#FFFFFF',
  minimum: '#E76F51',
  null: '#A0A0A0',
  firstLevelElements: '#0F4C81',
  secondLevelElements: '#374649',
  thirdLevelElements: '#A0A0A0',
  fourthLevelElements: '#D2D0CE',
  secondaryBackground: '#F0F6FB',
  visualStyles: {
    '*': { '*': {
      background: [{ show: false }],
      border: [{ show: false }],
      dropShadow: [{ show: false }],
      visualHeader: [{ show: true }],
      title: [{ show: true, fontFamily: 'Segoe UI', fontSize: 14, fontColor: { solid: { color: '#0F4C81' } }, alignment: 'left', background: { solid: { color: '#FFFFFF' } }, bold: true }],
    }},
    barChart: { '*': {
      legend: [{ show: true, position: 'Top', showTitle: false, labelColor: { solid: { color: '#444444' } }, fontFamily: 'Segoe UI', fontSize: 10 }],
      categoryAxis: [{ show: true, fontSize: 11, fontFamily: 'Segoe UI', showAxisTitle: false, labelColor: { solid: { color: '#666666' } }, gridlineShow: false }],
      valueAxis: [{ show: true, fontSize: 11, fontFamily: 'Segoe UI', showAxisTitle: false, labelColor: { solid: { color: '#666666' } }, gridlineShow: true, gridlineColor: { solid: { color: '#E0E0E0' } } }],
      plotArea: [{ transparency: 0 }],
      labels: [{ show: false, fontSize: 9, fontFamily: 'Segoe UI', color: { solid: { color: '#333333' } } }],
    }},
    clusteredBarChart: { '*': {
      legend: [{ show: true, position: 'Top', showTitle: false, labelColor: { solid: { color: '#444444' } }, fontFamily: 'Segoe UI', fontSize: 10 }],
      categoryAxis: [{ show: true, fontSize: 11, fontFamily: 'Segoe UI', showAxisTitle: false, labelColor: { solid: { color: '#666666' } } }],
      valueAxis: [{ show: true, fontSize: 11, fontFamily: 'Segoe UI', showAxisTitle: false, labelColor: { solid: { color: '#666666' } }, gridlineShow: true, gridlineColor: { solid: { color: '#E0E0E0' } } }],
      labels: [{ show: false, fontSize: 9, fontFamily: 'Segoe UI', color: { solid: { color: '#333333' } } }],
    }},
    stackedBarChart: { '*': {
      legend: [{ show: true, position: 'Top', showTitle: false, labelColor: { solid: { color: '#444444' } }, fontFamily: 'Segoe UI', fontSize: 10 }],
      categoryAxis: [{ show: true, fontSize: 11, fontFamily: 'Segoe UI', showAxisTitle: false, labelColor: { solid: { color: '#666666' } } }],
      valueAxis: [{ show: true, fontSize: 11, fontFamily: 'Segoe UI', showAxisTitle: false, labelColor: { solid: { color: '#666666' } }, gridlineShow: true, gridlineColor: { solid: { color: '#E0E0E0' } } }],
      labels: [{ show: false, fontSize: 9, fontFamily: 'Segoe UI', color: { solid: { color: '#333333' } } }],
    }},
    hundredPercentStackedBarChart: { '*': {
      legend: [{ show: true, position: 'Top', showTitle: false, labelColor: { solid: { color: '#444444' } }, fontFamily: 'Segoe UI', fontSize: 10 }],
      categoryAxis: [{ show: true, fontSize: 11, fontFamily: 'Segoe UI', showAxisTitle: false, labelColor: { solid: { color: '#666666' } } }],
      valueAxis: [{ show: true, fontSize: 11, fontFamily: 'Segoe UI', showAxisTitle: false, labelColor: { solid: { color: '#666666' } } }],
      labels: [{ show: true, fontSize: 9, fontFamily: 'Segoe UI', color: { solid: { color: '#333333' } } }],
    }},
    columnChart: { '*': {
      legend: [{ show: true, position: 'Top', showTitle: false, labelColor: { solid: { color: '#444444' } }, fontFamily: 'Segoe UI', fontSize: 10 }],
      categoryAxis: [{ show: true, fontSize: 11, fontFamily: 'Segoe UI', showAxisTitle: false, labelColor: { solid: { color: '#666666' } }, gridlineShow: false }],
      valueAxis: [{ show: true, fontSize: 11, fontFamily: 'Segoe UI', showAxisTitle: false, labelColor: { solid: { color: '#666666' } }, gridlineShow: true, gridlineColor: { solid: { color: '#E0E0E0' } } }],
      labels: [{ show: false, fontSize: 9, fontFamily: 'Segoe UI', color: { solid: { color: '#333333' } } }],
    }},
    clusteredColumnChart: { '*': {
      legend: [{ show: true, position: 'Top', showTitle: false, labelColor: { solid: { color: '#444444' } }, fontFamily: 'Segoe UI', fontSize: 10 }],
      categoryAxis: [{ show: true, fontSize: 11, fontFamily: 'Segoe UI', showAxisTitle: false, labelColor: { solid: { color: '#666666' } } }],
      valueAxis: [{ show: true, fontSize: 11, fontFamily: 'Segoe UI', showAxisTitle: false, labelColor: { solid: { color: '#666666' } }, gridlineShow: true, gridlineColor: { solid: { color: '#E0E0E0' } } }],
      labels: [{ show: false, fontSize: 9, fontFamily: 'Segoe UI', color: { solid: { color: '#333333' } } }],
    }},
    stackedColumnChart: { '*': {
      legend: [{ show: true, position: 'Top', showTitle: false, labelColor: { solid: { color: '#444444' } }, fontFamily: 'Segoe UI', fontSize: 10 }],
      categoryAxis: [{ show: true, fontSize: 11, fontFamily: 'Segoe UI', showAxisTitle: false, labelColor: { solid: { color: '#666666' } } }],
      valueAxis: [{ show: true, fontSize: 11, fontFamily: 'Segoe UI', showAxisTitle: false, labelColor: { solid: { color: '#666666' } }, gridlineShow: true, gridlineColor: { solid: { color: '#E0E0E0' } } }],
      labels: [{ show: false, fontSize: 9, fontFamily: 'Segoe UI', color: { solid: { color: '#333333' } } }],
    }},
    hundredPercentStackedColumnChart: { '*': {
      legend: [{ show: true, position: 'Top', showTitle: false, labelColor: { solid: { color: '#444444' } }, fontFamily: 'Segoe UI', fontSize: 10 }],
      categoryAxis: [{ show: true, fontSize: 11, fontFamily: 'Segoe UI', showAxisTitle: false, labelColor: { solid: { color: '#666666' } } }],
      valueAxis: [{ show: true, fontSize: 11, fontFamily: 'Segoe UI', showAxisTitle: false, labelColor: { solid: { color: '#666666' } } }],
      labels: [{ show: true, fontSize: 9, fontFamily: 'Segoe UI', color: { solid: { color: '#333333' } } }],
    }},
    lineChart: { '*': {
      legend: [{ show: true, position: 'Top', showTitle: false, labelColor: { solid: { color: '#444444' } }, fontFamily: 'Segoe UI', fontSize: 10 }],
      categoryAxis: [{ show: true, fontSize: 11, fontFamily: 'Segoe UI', showAxisTitle: false, labelColor: { solid: { color: '#666666' } } }],
      valueAxis: [{ show: true, fontSize: 11, fontFamily: 'Segoe UI', showAxisTitle: false, labelColor: { solid: { color: '#666666' } }, gridlineShow: true, gridlineColor: { solid: { color: '#E0E0E0' } } }],
      shapes: [{ strokeWidth: 2, showMarker: false, markerSize: 3 }],
      labels: [{ show: false, fontSize: 9, fontFamily: 'Segoe UI', color: { solid: { color: '#333333' } } }],
    }},
    areaChart: { '*': {
      legend: [{ show: true, position: 'Top', showTitle: false, labelColor: { solid: { color: '#444444' } }, fontFamily: 'Segoe UI', fontSize: 10 }],
      categoryAxis: [{ show: true, fontSize: 11, fontFamily: 'Segoe UI', showAxisTitle: false, labelColor: { solid: { color: '#666666' } } }],
      valueAxis: [{ show: true, fontSize: 11, fontFamily: 'Segoe UI', showAxisTitle: false, labelColor: { solid: { color: '#666666' } }, gridlineShow: true, gridlineColor: { solid: { color: '#E0E0E0' } } }],
      labels: [{ show: false, fontSize: 9, fontFamily: 'Segoe UI', color: { solid: { color: '#333333' } } }],
    }},
    stackedAreaChart: { '*': {
      legend: [{ show: true, position: 'Top', showTitle: false, labelColor: { solid: { color: '#444444' } }, fontFamily: 'Segoe UI', fontSize: 10 }],
      categoryAxis: [{ show: true, fontSize: 11, fontFamily: 'Segoe UI', showAxisTitle: false, labelColor: { solid: { color: '#666666' } } }],
      valueAxis: [{ show: true, fontSize: 11, fontFamily: 'Segoe UI', showAxisTitle: false, labelColor: { solid: { color: '#666666' } }, gridlineShow: true, gridlineColor: { solid: { color: '#E0E0E0' } } }],
      labels: [{ show: false, fontSize: 9, fontFamily: 'Segoe UI', color: { solid: { color: '#333333' } } }],
    }},
    ribbonChart: { '*': {
      legend: [{ show: true, position: 'Top', showTitle: false, labelColor: { solid: { color: '#444444' } }, fontFamily: 'Segoe UI', fontSize: 10 }],
      categoryAxis: [{ show: true, fontSize: 11, fontFamily: 'Segoe UI', showAxisTitle: false, labelColor: { solid: { color: '#666666' } } }],
      valueAxis: [{ show: true, fontSize: 11, fontFamily: 'Segoe UI', showAxisTitle: false, labelColor: { solid: { color: '#666666' } }, gridlineShow: true, gridlineColor: { solid: { color: '#E0E0E0' } } }],
      labels: [{ show: false, fontSize: 9, fontFamily: 'Segoe UI', color: { solid: { color: '#333333' } } }],
    }},
    waterfallChart: { '*': {
      legend: [{ show: true, position: 'Top', showTitle: false, labelColor: { solid: { color: '#444444' } }, fontFamily: 'Segoe UI', fontSize: 10 }],
      categoryAxis: [{ show: true, fontSize: 11, fontFamily: 'Segoe UI', showAxisTitle: false, labelColor: { solid: { color: '#666666' } } }],
      valueAxis: [{ show: true, fontSize: 11, fontFamily: 'Segoe UI', showAxisTitle: false, labelColor: { solid: { color: '#666666' } }, gridlineShow: true, gridlineColor: { solid: { color: '#E0E0E0' } } }],
      sentimentColors: [{ increaseFill: { solid: { color: '#2A9D8F' } }, decreaseFill: { solid: { color: '#E76F51' } }, totalFill: { solid: { color: '#0F4C81' } } }],
      labels: [{ show: true, fontSize: 9, fontFamily: 'Segoe UI', color: { solid: { color: '#333333' } } }],
    }},
    scatterChart: { '*': {
      legend: [{ show: true, position: 'Top', showTitle: false, labelColor: { solid: { color: '#444444' } }, fontFamily: 'Segoe UI', fontSize: 10 }],
      categoryAxis: [{ show: true, fontSize: 11, fontFamily: 'Segoe UI', showAxisTitle: false, labelColor: { solid: { color: '#666666' } }, gridlineShow: true, gridlineColor: { solid: { color: '#E0E0E0' } } }],
      valueAxis: [{ show: true, fontSize: 11, fontFamily: 'Segoe UI', showAxisTitle: false, labelColor: { solid: { color: '#666666' } }, gridlineShow: true, gridlineColor: { solid: { color: '#E0E0E0' } } }],
      fillPoint: [{ show: true }],
      labels: [{ show: false, fontSize: 9, fontFamily: 'Segoe UI', color: { solid: { color: '#333333' } } }],
    }},
    pieChart: { '*': {
      legend: [{ show: true, position: 'Right', showTitle: false, labelColor: { solid: { color: '#444444' } }, fontFamily: 'Segoe UI', fontSize: 10 }],
      detail: [{ show: false }],
      labels: [{ show: true, fontSize: 10, fontFamily: 'Segoe UI', color: { solid: { color: '#333333' } }, labelDisplayUnits: 0, labelStyle: 'category' }],
    }},
    donutChart: { '*': {
      legend: [{ show: true, position: 'Right', showTitle: false, labelColor: { solid: { color: '#444444' } }, fontFamily: 'Segoe UI', fontSize: 10 }],
      innerRadius: [{ innerRadiusRatio: 50 }],
      labels: [{ show: true, fontSize: 10, fontFamily: 'Segoe UI', color: { solid: { color: '#333333' } }, labelStyle: 'category' }],
    }},
    treemap: { '*': {
      legend: [{ show: true, position: 'Top', showTitle: false, labelColor: { solid: { color: '#444444' } }, fontFamily: 'Segoe UI', fontSize: 10 }],
      categoryLabels: [{ show: true, fontSize: 10, fontFamily: 'Segoe UI', color: { solid: { color: '#333333' } } }],
      labels: [{ show: true, fontSize: 10, fontFamily: 'Segoe UI', color: { solid: { color: '#333333' } } }],
    }},
    azureMap: { '*': {
      legend: [{ show: true, position: 'Top', showTitle: false, labelColor: { solid: { color: '#444444' } }, fontFamily: 'Segoe UI', fontSize: 10 }],
      bubbles: [{ minBubbleSize: 10, maxBubbleSize: 40 }],
      labels: [{ show: false, fontSize: 9, fontFamily: 'Segoe UI', color: { solid: { color: '#333333' } } }],
    }},
    funnel: { '*': {
      legend: [{ show: false }],
      labels: [{ show: true, fontSize: 10, fontFamily: 'Segoe UI', color: { solid: { color: '#333333' } }, labelStyle: 'both' }],
    }},
    gauge: { '*': {
      dataLabels: [{ show: true, fontSize: 24, fontFamily: 'Segoe UI', color: { solid: { color: '#0F4C81' } } }],
      gauge: [{ arcAngle: 150, startAngle: -150, pinNeedle: false, targetColor: { solid: { color: '#E76F51' } }, foregroundColor: { solid: { color: '#1F8AC0' } }, backgroundColor: { solid: { color: '#E0E0E0' } } }],
      target: [{ show: true, fontSize: 12, fontFamily: 'Segoe UI', color: { solid: { color: '#666666' } } }],
    }},
    card: { '*': {
      dataLabels: [{ show: true, fontSize: 32, fontFamily: 'Segoe UI Light', color: { solid: { color: '#0F4C81' } }, labelDisplayUnits: 0 }],
      categoryLabels: [{ show: true, fontSize: 12, fontFamily: 'Segoe UI', color: { solid: { color: '#666666' } } }],
      wordWrap: [{ show: false }],
    }},
    multiRowCard: { '*': {
      dataLabels: [{ fontSize: 14, fontFamily: 'Segoe UI', color: { solid: { color: '#0F4C81' } } }],
      categoryLabels: [{ show: true, fontSize: 10, fontFamily: 'Segoe UI', color: { solid: { color: '#666666' } } }],
      cardTitle: [{ show: true, fontSize: 12, fontFamily: 'Segoe UI Semibold', color: { solid: { color: '#0F4C81' } } }],
      outline: [{ show: true, color: { solid: { color: '#E0E0E0' } }, weight: 1 }],
      bar: [{ show: true, color: { solid: { color: '#1F8AC0' } }, weight: 4 }],
    }},
    kpi: { '*': {
      indicator: [{ show: true, thickness: 3 }],
      trendline: [{ show: true, color: { solid: { color: '#1F8AC0' } } }],
      dataLabels: [{ show: true, fontSize: 28, fontFamily: 'Segoe UI Light', color: { solid: { color: '#0F4C81' } } }],
      goals: [{ show: true, fontSize: 12, fontFamily: 'Segoe UI', color: { solid: { color: '#666666' } } }],
      statusGraphic: [{ show: true }],
    }},
    slicer: { '*': {
      data: [{ fontFamily: 'Segoe UI', fontSize: 12, fontColor: { solid: { color: '#333333' } } }],
      selection: [{ selectAllCheckboxEnabled: false, singleSelect: true }],
      slicerHeader: [{ show: true, fontFamily: 'Segoe UI Semibold', fontColor: { solid: { color: '#0F4C81' } }, background: { solid: { color: '#FFFFFF' } }, outline: 'None', textSize: 12 }],
      slicerItems: [{ fontFamily: 'Segoe UI', fontColor: { solid: { color: '#333333' } }, background: { solid: { color: '#FFFFFF' } }, outline: 'Frame', textSize: 11 }],
    }},
    tableEx: { '*': {
      grid: [{ outlineColor: { solid: { color: '#E0E0E0' } }, outlineWeight: 1, gridVertical: false, gridHorizontal: true, gridHorizontalColor: { solid: { color: '#E0E0E0' } }, gridHorizontalWeight: 1, rowPadding: 4 }],
      columnHeaders: [{ fontFamily: 'Segoe UI Semibold', fontSize: 11, fontColor: { solid: { color: '#FFFFFF' } }, outline: 'None', alignment: 'left', backColor: { solid: { color: '#0F4C81' } } }],
      values: [{ fontFamily: 'Segoe UI', fontSize: 11, fontColor: { solid: { color: '#333333' } }, alignment: 'left', backColor: { solid: { color: '#FFFFFF' } }, backColorSecondary: { solid: { color: '#F0F6FB' } } }],
      total: [{ totals: true, fontFamily: 'Segoe UI Semibold', fontSize: 11, fontColor: { solid: { color: '#0F4C81' } }, outline: 'Top', outlineColor: { solid: { color: '#0F4C81' } }, backColor: { solid: { color: '#E8F0F7' } } }],
    }},
    pivotTable: { '*': {
      title: [{ show: true, fontFamily: 'Segoe UI', fontSize: 14, fontColor: { solid: { color: '#0F4C81' } }, alignment: 'left', bold: true }],
      grid: [{ outlineColor: { solid: { color: '#E0E0E0' } }, outlineWeight: 1, gridVertical: false, gridHorizontal: true, gridHorizontalColor: { solid: { color: '#E0E0E0' } }, gridHorizontalWeight: 1, rowPadding: 4 }],
      rowHeaders: [{ fontFamily: 'Segoe UI', fontSize: 11, fontColor: { solid: { color: '#333333' } }, outline: 'None', stepped: true, steppedLayoutIndentation: 20, expandCollapse: true, backColor: { solid: { color: '#FFFFFF' } } }],
      columnHeaders: [{ fontFamily: 'Segoe UI Semibold', fontSize: 11, fontColor: { solid: { color: '#FFFFFF' } }, outline: 'None', alignment: 'left', backColor: { solid: { color: '#0F4C81' } } }],
      values: [{ fontFamily: 'Segoe UI', fontSize: 11, fontColor: { solid: { color: '#333333' } }, alignment: 'right', backColor: { solid: { color: '#FFFFFF' } }, backColorSecondary: { solid: { color: '#F0F6FB' } } }],
      subTotals: [{ rowSubtotals: true, columnSubtotals: true, fontFamily: 'Segoe UI Semibold', fontSize: 11, fontColor: { solid: { color: '#0F4C81' } }, outline: 'TopBottom', outlineColor: { solid: { color: '#0F4C81' } }, perRowLevel: true, perColumnLevel: true, backColor: { solid: { color: '#E8F0F7' } } }],
    }},
    lineClusteredColumnComboChart: { '*': {
      legend: [{ show: true, position: 'Top', showTitle: false, labelColor: { solid: { color: '#444444' } }, fontFamily: 'Segoe UI', fontSize: 10 }],
      categoryAxis: [{ show: true, fontSize: 11, fontFamily: 'Segoe UI', showAxisTitle: false, labelColor: { solid: { color: '#666666' } } }],
      valueAxis: [{ show: true, fontSize: 11, fontFamily: 'Segoe UI', showAxisTitle: false, labelColor: { solid: { color: '#666666' } }, gridlineShow: true, gridlineColor: { solid: { color: '#E0E0E0' } } }],
      y2AxisReferenceLine: [{ show: false }],
      labels: [{ show: false, fontSize: 9, fontFamily: 'Segoe UI', color: { solid: { color: '#333333' } } }],
    }},
    lineStackedColumnComboChart: { '*': {
      legend: [{ show: true, position: 'Top', showTitle: false, labelColor: { solid: { color: '#444444' } }, fontFamily: 'Segoe UI', fontSize: 10 }],
      categoryAxis: [{ show: true, fontSize: 11, fontFamily: 'Segoe UI', showAxisTitle: false, labelColor: { solid: { color: '#666666' } } }],
      valueAxis: [{ show: true, fontSize: 11, fontFamily: 'Segoe UI', showAxisTitle: false, labelColor: { solid: { color: '#666666' } }, gridlineShow: true, gridlineColor: { solid: { color: '#E0E0E0' } } }],
      labels: [{ show: false, fontSize: 9, fontFamily: 'Segoe UI', color: { solid: { color: '#333333' } } }],
    }},
    decompositionTree: { '*': {
      legend: [{ show: true, position: 'Top', showTitle: false, labelColor: { solid: { color: '#444444' } }, fontFamily: 'Segoe UI', fontSize: 10 }],
      dataLabels: [{ show: true, fontSize: 11, fontFamily: 'Segoe UI', color: { solid: { color: '#333333' } } }],
      header: [{ fontFamily: 'Segoe UI Semibold', fontSize: 11, fontColor: { solid: { color: '#FFFFFF' } }, fill: { solid: { color: '#0F4C81' } } }],
    }},
    shape: { '*': {
      fill: [{ show: true, fillColor: { solid: { color: '#1F8AC0' } }, transparency: 0 }],
      shapeOutline: [{ show: false, lineColor: { solid: { color: '#0F4C81' } }, weight: 1 }],
    }},
    textbox: { '*': {
      background: [{ show: false }],
      border: [{ show: false }],
    }},
    image: { '*': {
      imageScaling: [{ imageScalingType: 'Fit' }],
      background: [{ show: false }],
    }},
    actionButton: { '*': {
      text: [{ show: true, fontFamily: 'Segoe UI', fontSize: 12, fontColor: { solid: { color: '#FFFFFF' } }, alignment: 'center', verticalAlignment: 'middle', bold: false }],
      fill: [{ show: true, transparency: 0, fillColor: { solid: { color: '#1F8AC0' } } }],
      outline: [{ show: false }],
      shadow: [{ show: false }],
    }},
  },
};

export const SEMANTIC_KEYS = [
  'background', 'foreground', 'tableAccent',
  'good', 'neutral', 'bad',
  'maximum', 'center', 'minimum', 'null',
  'firstLevelElements', 'secondLevelElements', 'thirdLevelElements', 'fourthLevelElements', 'secondaryBackground',
];

export const TEXT_CLASSES = ['title', 'header', 'label', 'callout'];
