import { FONTS } from './enums.js';

export const CARD_DEFS = {
  general: [
    { key:'responsive',    type:'boolean', label:'Responsive',     def:true },
    { key:'outlineColor',  type:'color',   label:'Outline Color',  def:'#E0E0E0' },
    { key:'outlineWeight', type:'number',  label:'Outline Weight', def:1, min:0, max:10 },
    { key:'formatString',  type:'string',  label:'Format String',  def:'' },
  ],
  title: [
    { key:'show',        type:'boolean',  label:'Show Title',    def:true },
    { key:'fontFamily',  type:'enum',     label:'Font Family',   def:'Segoe UI',  options:FONTS },
    { key:'fontSize',    type:'number',   label:'Font Size',     def:14, min:6, max:96 },
    { key:'fontColor',   type:'color',    label:'Font Color',    def:'#0F4C81' },
    { key:'bold',        type:'boolean',  label:'Bold',          def:true },
    { key:'italic',      type:'boolean',  label:'Italic',        def:false },
    { key:'underline',   type:'boolean',  label:'Underline',     def:false },
    { key:'titleWrap',   type:'boolean',  label:'Word Wrap',     def:false },
    { key:'alignment',   type:'enum',     label:'Alignment',     def:'left', options:['left','center','right'] },
    { key:'background',  type:'color',    label:'Background',    def:'#FFFFFF' },
    { key:'heading',     type:'enum',     label:'Heading Style', def:'None', options:['None','H1','H2','H3','H4'] },
  ],
  subheader: [
    { key:'show',       type:'boolean', label:'Show Subtitle', def:false },
    { key:'fontFamily', type:'enum',    label:'Font Family',   def:'Segoe UI', options:FONTS },
    { key:'fontSize',   type:'number',  label:'Font Size',     def:11, min:6, max:96 },
    { key:'fontColor',  type:'color',   label:'Font Color',    def:'#666666' },
    { key:'bold',       type:'boolean', label:'Bold',          def:false },
    { key:'italic',     type:'boolean', label:'Italic',        def:false },
    { key:'alignment',  type:'enum',    label:'Alignment',     def:'left', options:['left','center','right'] },
  ],
  legend: [
    { key:'show',       type:'boolean', label:'Show Legend',  def:true },
    { key:'position',   type:'enum',    label:'Position',     def:'Top', options:['Top','TopCenter','TopRight','Bottom','BottomCenter','BottomRight','Left','LeftCenter','Right','RightCenter'] },
    { key:'showTitle',          type:'boolean', label:'Show Title',        def:false },
    { key:'labelColor',         type:'color',   label:'Label Color',       def:'#444444' },
    { key:'fontFamily',         type:'enum',    label:'Font Family',       def:'Segoe UI', options:FONTS },
    { key:'fontSize',           type:'number',  label:'Font Size',         def:10, min:6, max:40 },
    { key:'bold',               type:'boolean', label:'Bold',              def:false },
    { key:'italic',             type:'boolean', label:'Italic',            def:false },
    { key:'underline',          type:'boolean', label:'Underline',         def:false },
    { key:'matchLineColor',     type:'boolean', label:'Match Line Color',  def:false },
    { key:'legendMarkerRendering', type:'enum', label:'Marker Style',      def:'markerOnly', options:['markerOnly','lineAndMarker','lineOnly'] },
    { key:'showGradientLegend', type:'boolean', label:'Gradient Legend',   def:false },
  ],
  categoryAxis: [
    { key:'show',             type:'boolean', label:'Show Axis',          def:true },
    { key:'axisType',         type:'enum',    label:'Axis Type',          def:'Categorical', options:['Categorical','Continuous'] },
    { key:'axisStyle',        type:'enum',    label:'Axis Style',         def:'showTitleOnly', options:['showTitleOnly','showUnitOnly','showBoth'] },
    { key:'labelColor',       type:'color',   label:'Label Color',        def:'#666666' },
    { key:'fontFamily',       type:'enum',    label:'Font Family',        def:'Segoe UI', options:FONTS },
    { key:'fontSize',         type:'number',  label:'Font Size',          def:11, min:6, max:40 },
    { key:'bold',             type:'boolean', label:'Bold',               def:false },
    { key:'italic',           type:'boolean', label:'Italic',             def:false },
    { key:'underline',        type:'boolean', label:'Underline',          def:false },
    { key:'roundRange',       type:'boolean', label:'Round Range',        def:false },
    { key:'showAxisTitle',      type:'boolean', label:'Show Axis Title',      def:false },
    { key:'titleColor',         type:'color',   label:'Title Color',          def:'#666666' },
    { key:'titleFontFamily',    type:'enum',    label:'Title Font Family',    def:'Segoe UI', options:FONTS },
    { key:'titleFontSize',      type:'number',  label:'Title Font Size',      def:11, min:6, max:40 },
    { key:'titleBold',          type:'boolean', label:'Title Bold',           def:false },
    { key:'titleItalic',        type:'boolean', label:'Title Italic',         def:false },
    { key:'titleUnderline',     type:'boolean', label:'Title Underline',      def:false },
    { key:'gridlineShow',       type:'boolean', label:'Show Gridlines',       def:false },
    { key:'gridlineColor',      type:'color',   label:'Gridline Color',       def:'#E0E0E0' },
    { key:'gridlineThickness',  type:'number',  label:'Gridline Thickness',   def:1, min:1, max:10 },
    { key:'gridlineStyle',      type:'enum',    label:'Gridline Style',       def:'dashed', options:['solid','dashed','dotted'] },
    { key:'gridlineAutoScale',  type:'boolean', label:'Auto Scale Gridlines', def:false },
    { key:'gridlineTransparency',type:'number', label:'Gridline Transparency',def:0, min:0, max:100 },
    { key:'labelDisplayUnits',  type:'enum',    label:'Display Units',        def:'0', options:['0','1000','1000000','1000000000','1000000000000'] },
    { key:'labelPrecision',     type:'number',  label:'Decimal Places',       def:0, min:0, max:10 },
    { key:'invertAxis',         type:'boolean', label:'Invert Axis',          def:false },
    { key:'concatenateLabels',  type:'boolean', label:'Concatenate Labels',   def:false },
    { key:'innerPadding',       type:'number',  label:'Inner Padding',        def:0, min:0, max:50 },
    { key:'switchAxisPosition', type:'boolean', label:'Switch Position',      def:false },
    { key:'preferredCategoryWidth', type:'number', label:'Category Width',    def:0, min:0, max:500 },
    { key:'maxMarginFactor',    type:'number',  label:'Max Margin Factor',    def:25, min:0, max:100 },
  ],
  valueAxis: [
    { key:'show',            type:'boolean', label:'Show Axis',         def:true },
    { key:'axisStyle',       type:'enum',    label:'Axis Style',        def:'showTitleOnly', options:['showTitleOnly','showUnitOnly','showBoth'] },
    { key:'labelColor',      type:'color',   label:'Label Color',       def:'#666666' },
    { key:'fontFamily',      type:'enum',    label:'Font Family',       def:'Segoe UI', options:FONTS },
    { key:'fontSize',        type:'number',  label:'Font Size',         def:11, min:6, max:40 },
    { key:'bold',            type:'boolean', label:'Bold',              def:false },
    { key:'italic',          type:'boolean', label:'Italic',            def:false },
    { key:'underline',       type:'boolean', label:'Underline',         def:false },
    { key:'roundRange',      type:'boolean', label:'Round Range',       def:false },
    { key:'sharedAxis',      type:'boolean', label:'Shared Axis',       def:false },
    { key:'showAxisTitle',   type:'boolean', label:'Show Axis Title',   def:false },
    { key:'titleColor',      type:'color',   label:'Title Color',       def:'#666666' },
    { key:'titleFontFamily', type:'enum',    label:'Title Font Family', def:'Segoe UI', options:FONTS },
    { key:'titleFontSize',   type:'number',  label:'Title Font Size',   def:11, min:6, max:40 },
    { key:'gridlineShow',        type:'boolean', label:'Show Gridlines',       def:true },
    { key:'gridlineColor',       type:'color',   label:'Gridline Color',       def:'#E0E0E0' },
    { key:'gridlineThickness',   type:'number',  label:'Gridline Thickness',   def:1, min:1, max:10 },
    { key:'gridlineStyle',       type:'enum',    label:'Gridline Style',       def:'dashed', options:['solid','dashed','dotted'] },
    { key:'gridlineTransparency',type:'number',  label:'Gridline Transparency',def:0, min:0, max:100 },
    { key:'logAxisScale',        type:'boolean', label:'Log Scale',            def:false },
    { key:'invertAxis',          type:'boolean', label:'Invert Axis',          def:false },
    { key:'scaleToFit',          type:'boolean', label:'Scale to Fit',         def:false },
    { key:'start',               type:'number',  label:'Axis Start',           def:0, min:-1e9, max:1e9 },
    { key:'end',                 type:'number',  label:'Axis End',             def:0, min:-1e9, max:1e9 },
    { key:'labelDisplayUnits',   type:'enum',    label:'Display Units',        def:'0', options:['0','1000','1000000','1000000000','1000000000000'] },
    { key:'labelPrecision',      type:'number',  label:'Decimal Places',       def:0, min:0, max:10 },
    { key:'titleBold',           type:'boolean', label:'Title Bold',           def:false },
    { key:'titleItalic',         type:'boolean', label:'Title Italic',         def:false },
  ],
  labels: [
    { key:'show',              type:'boolean', label:'Show Labels',       def:false },
    { key:'color',             type:'color',   label:'Label Color',       def:'#FFFFFF' },
    { key:'fontFamily',        type:'enum',    label:'Font Family',       def:'Segoe UI', options:FONTS },
    { key:'fontSize',          type:'number',  label:'Font Size',         def:9, min:6, max:40 },
    { key:'bold',              type:'boolean', label:'Bold',              def:false },
    { key:'italic',            type:'boolean', label:'Italic',            def:false },
    { key:'labelDisplayUnits', type:'enum',    label:'Display Units',     def:'0', options:['0','1000','1000000','1000000000','1000000000000'] },
    { key:'labelPrecision',    type:'number',  label:'Decimal Places',    def:0, min:0, max:10 },
    { key:'labelPosition',     type:'enum',    label:'Position',          def:'InsideEnd', options:['InsideEnd','InsideCenter','InsideBase','OutsideEnd','Auto'] },
    { key:'labelStyle',           type:'enum',    label:'Label Style',          def:'category', options:['category','data','both','percent','percentOfTotal'] },
    { key:'wordWrap',             type:'boolean', label:'Word Wrap',            def:false },
    { key:'backgroundColor',      type:'color',   label:'Background Color',     def:'#FFFFFF' },
    { key:'backgroundTransparency',type:'number', label:'Bg Transparency',      def:100, min:0, max:100 },
    { key:'enableBackground',     type:'boolean', label:'Enable Background',    def:false },
    { key:'labelDensity',         type:'number',  label:'Label Density',        def:100, min:0, max:100 },
    { key:'labelOrientation',     type:'enum',    label:'Orientation',          def:'horizontal', options:['horizontal','vertical','diagonal'] },
    { key:'labelOverflow',        type:'boolean', label:'Allow Overflow',       def:false },
    { key:'showAll',              type:'boolean', label:'Show All',             def:false },
    { key:'showBlankAs',          type:'string',  label:'Show Blank As',        def:'' },
    { key:'showSeries',           type:'boolean', label:'Show Series Name',     def:false },
    { key:'showDynamicLabels',    type:'boolean', label:'Dynamic Labels',       def:false },
    { key:'optimizeLabelDisplay', type:'boolean', label:'Optimize Display',     def:false },
    { key:'valueCustomFormatString', type:'string', label:'Custom Format',      def:'' },
    { key:'detailBold',           type:'boolean', label:'Detail Bold',          def:false },
    { key:'detailColor',          type:'color',   label:'Detail Color',         def:'#444444' },
    { key:'detailFontFamily',     type:'enum',    label:'Detail Font Family',   def:'Segoe UI', options:FONTS },
    { key:'detailFontSize',       type:'number',  label:'Detail Font Size',     def:9, min:6, max:40 },
    { key:'detailItalic',         type:'boolean', label:'Detail Italic',        def:false },
    { key:'enableDetailDataLabel',type:'boolean', label:'Enable Detail Label',  def:false },
    { key:'titleBold',            type:'boolean', label:'Title Bold',           def:false },
    { key:'titleColor',           type:'color',   label:'Title Color',          def:'#444444' },
    { key:'titleFontFamily',      type:'enum',    label:'Title Font Family',    def:'Segoe UI', options:FONTS },
    { key:'titleFontSize',        type:'number',  label:'Title Font Size',      def:9, min:6, max:40 },
    { key:'labelContainerMaxWidth', type:'number',label:'Max Width',            def:0, min:0, max:500 },
  ],
  dataPoint: [
    { key:'defaultColor',         type:'color',   label:'Default Color',      def:'#0F4C81' },
    { key:'fillTransparency',     type:'number',  label:'Fill Transparency',  def:0, min:0, max:100 },
    { key:'borderShow',           type:'boolean', label:'Show Border',        def:false },
    { key:'borderColor',          type:'color',   label:'Border Color',       def:'#FFFFFF' },
    { key:'borderSize',           type:'number',  label:'Border Size',        def:1, min:0, max:10 },
    { key:'borderTransparency',   type:'number',  label:'Border Transparency',def:0, min:0, max:100 },
    { key:'borderColorMatchFill', type:'boolean', label:'Border Matches Fill',def:false },
  ],
  plotArea: [
    { key:'transparency', type:'number', label:'Transparency', def:0, min:0, max:100 },
    { key:'image',        type:'string', label:'Image URL',    def:'' },
  ],
  lineStyles: [
    { key:'strokeWidth',  type:'number',  label:'Line Width',   def:2, min:1, max:10 },
    { key:'lineStyle',    type:'enum',    label:'Line Style',   def:'solid', options:['solid','dashed','dotted'] },
    { key:'showMarker',   type:'boolean', label:'Show Markers', def:false },
    { key:'markerSize',   type:'number',  label:'Marker Size',  def:3, min:1, max:20 },
    { key:'markerShape',  type:'enum',    label:'Marker Shape', def:'circle', options:['circle','square','diamond','triangle','x'] },
  ],
  trend: [
    { key:'show',       type:'boolean', label:'Show Trend Line', def:false },
    { key:'lineColor',  type:'color',   label:'Line Color',      def:'#E76F51' },
    { key:'lineWidth',  type:'number',  label:'Line Width',      def:2, min:1, max:10 },
    { key:'lineStyle',  type:'enum',    label:'Line Style',      def:'dashed', options:['solid','dashed','dotted'] },
  ],
  background: [
    { key:'show',         type:'boolean', label:'Show Background', def:false },
    { key:'color',        type:'color',   label:'Color',           def:'#FFFFFF' },
    { key:'transparency', type:'number',  label:'Transparency',    def:0, min:0, max:100 },
  ],
  border: [
    { key:'show',   type:'boolean', label:'Show Border',    def:false },
    { key:'color',  type:'color',   label:'Border Color',   def:'#E0E0E0' },
    { key:'radius', type:'number',  label:'Corner Radius',  def:0, min:0, max:50 },
    { key:'weight', type:'number',  label:'Border Weight',  def:1, min:1, max:10 },
  ],
  shadow: [
    { key:'show',    type:'boolean', label:'Show Shadow',    def:false },
    { key:'color',   type:'color',   label:'Shadow Color',   def:'#000000' },
    { key:'preset',  type:'enum',    label:'Shadow Preset',  def:'BottomRight', options:['TopLeft','Top','TopRight','Left','Center','Right','BottomLeft','Bottom','BottomRight','Custom'] },
    { key:'shadowBlur',  type:'number', label:'Blur',        def:4, min:0, max:20 },
    { key:'shadowAngle', type:'number', label:'Angle',       def:45, min:0, max:360 },
    { key:'shadowDistance', type:'number', label:'Distance', def:2, min:0, max:20 },
  ],
  header: [
    { key:'show',       type:'boolean', label:'Show Header',  def:true },
    { key:'fontFamily', type:'enum',    label:'Font Family',  def:'Segoe UI Semibold', options:FONTS },
    { key:'fontSize',   type:'number',  label:'Font Size',    def:12, min:6, max:40 },
    { key:'fontColor',  type:'color',   label:'Font Color',   def:'#0F4C81' },
    { key:'bold',       type:'boolean', label:'Bold',         def:true },
    { key:'italic',     type:'boolean', label:'Italic',       def:false },
    { key:'underline',  type:'boolean', label:'Underline',    def:false },
    { key:'background', type:'color',   label:'Background',   def:'#FFFFFF' },
    { key:'outline',    type:'enum',    label:'Outline',      def:'None', options:['None','Frame','Top','Bottom','Left','Right','TopBottom'] },
  ],
  items: [
    { key:'fontFamily',  type:'enum',   label:'Font Family',  def:'Segoe UI', options:FONTS },
    { key:'fontSize',    type:'number', label:'Font Size',    def:11, min:6, max:40 },
    { key:'fontColor',   type:'color',  label:'Font Color',   def:'#333333' },
    { key:'bold',        type:'boolean',label:'Bold',         def:false },
    { key:'italic',      type:'boolean',label:'Italic',       def:false },
    { key:'background',  type:'color',  label:'Background',   def:'#FFFFFF' },
    { key:'outline',     type:'enum',   label:'Outline Style',def:'Frame', options:['None','Frame','Top','Bottom','Left','Right','TopBottom'] },
    { key:'padding',     type:'number', label:'Padding',      def:3, min:0, max:20 },
  ],
  selection: [
    { key:'singleSelect',              type:'boolean', label:'Single Select',          def:true },
    { key:'selectAllCheckboxEnabled',  type:'boolean', label:'Select All Checkbox',    def:false },
    { key:'selfFilterEnabled',         type:'boolean', label:'Self Filter',            def:false },
  ],
  grid: [
    { key:'outlineColor',          type:'color',   label:'Outline Color',         def:'#E0E0E0' },
    { key:'outlineWeight',         type:'number',  label:'Outline Weight',        def:1, min:1, max:10 },
    { key:'gridVertical',          type:'boolean', label:'Vertical Gridlines',    def:false },
    { key:'gridVerticalColor',     type:'color',   label:'Vertical Color',        def:'#E0E0E0' },
    { key:'gridHorizontal',        type:'boolean', label:'Horizontal Gridlines',  def:true },
    { key:'gridHorizontalColor',   type:'color',   label:'Horizontal Color',      def:'#E0E0E0' },
    { key:'gridHorizontalWeight',  type:'number',  label:'Horizontal Weight',     def:1, min:1, max:10 },
    { key:'rowPadding',            type:'number',  label:'Row Padding',           def:4, min:0, max:20 },
    { key:'imageHeight',           type:'number',  label:'Image Height',          def:75, min:10, max:200 },
  ],
  columnHeaders: [
    { key:'fontFamily',  type:'enum',   label:'Font Family',  def:'Segoe UI Semibold', options:FONTS },
    { key:'fontSize',    type:'number', label:'Font Size',    def:11, min:6, max:40 },
    { key:'fontColor',   type:'color',  label:'Font Color',   def:'#FFFFFF' },
    { key:'bold',        type:'boolean',label:'Bold',         def:true },
    { key:'italic',      type:'boolean',label:'Italic',       def:false },
    { key:'underline',   type:'boolean',label:'Underline',    def:false },
    { key:'backColor',   type:'color',  label:'Background',   def:'#0F4C81' },
    { key:'outline',     type:'enum',   label:'Outline',      def:'None', options:['None','Frame','Top','Bottom','Left','Right','TopBottom'] },
    { key:'alignment',   type:'enum',   label:'Alignment',    def:'left', options:['left','center','right'] },
    { key:'autoSizeColumnWidth', type:'boolean', label:'Auto Width', def:true },
  ],
  rowHeaders: [
    { key:'fontFamily',               type:'enum',   label:'Font Family',          def:'Segoe UI', options:FONTS },
    { key:'fontSize',                 type:'number', label:'Font Size',            def:11, min:6, max:40 },
    { key:'fontColor',                type:'color',  label:'Font Color',           def:'#333333' },
    { key:'bold',                     type:'boolean',label:'Bold',                 def:false },
    { key:'italic',                   type:'boolean',label:'Italic',               def:false },
    { key:'backColor',               type:'color',  label:'Background',           def:'#FFFFFF' },
    { key:'outline',                  type:'enum',   label:'Outline',              def:'None', options:['None','Frame','Top','Bottom','Left','Right','TopBottom'] },
    { key:'stepped',                  type:'boolean',label:'Stepped Layout',       def:true },
    { key:'steppedLayoutIndentation', type:'number', label:'Step Indent',          def:20, min:0, max:100 },
    { key:'expandCollapse',           type:'boolean',label:'Expand/Collapse',      def:true },
  ],
  values: [
    { key:'fontFamily',     type:'enum',   label:'Font Family',     def:'Segoe UI', options:FONTS },
    { key:'fontSize',       type:'number', label:'Font Size',       def:11, min:6, max:40 },
    { key:'fontColor',      type:'color',  label:'Font Color',      def:'#333333' },
    { key:'bold',           type:'boolean',label:'Bold',            def:false },
    { key:'italic',         type:'boolean',label:'Italic',          def:false },
    { key:'backColor',           type:'color',  label:'Background',      def:'#FFFFFF' },
    { key:'backColorSecondary',  type:'color',  label:'Banded Row Color',def:'#F0F6FB' },
    { key:'alignment',           type:'enum',   label:'Alignment',       def:'left', options:['left','center','right'] },
  ],
  subTotals: [
    { key:'rowSubtotals',    type:'boolean', label:'Row Subtotals',    def:true },
    { key:'columnSubtotals', type:'boolean', label:'Column Subtotals', def:true },
    { key:'fontFamily',      type:'enum',    label:'Font Family',      def:'Segoe UI Semibold', options:FONTS },
    { key:'fontSize',        type:'number',  label:'Font Size',        def:11, min:6, max:40 },
    { key:'fontColor',       type:'color',   label:'Font Color',       def:'#0F4C81' },
    { key:'bold',            type:'boolean', label:'Bold',             def:true },
    { key:'backColor',       type:'color',   label:'Background',       def:'#E8F0F7' },
    { key:'outline',         type:'enum',    label:'Outline',          def:'TopBottom', options:['None','Frame','Top','Bottom','Left','Right','TopBottom'] },
    { key:'outlineColor',    type:'color',   label:'Outline Color',    def:'#0F4C81' },
    { key:'perRowLevel',     type:'boolean', label:'Per Row Level',    def:true },
    { key:'perColumnLevel',  type:'boolean', label:'Per Column Level', def:true },
  ],
  total: [
    { key:'totals',     type:'boolean', label:'Show Totals',  def:true },
    { key:'fontFamily', type:'enum',    label:'Font Family',  def:'Segoe UI Semibold', options:FONTS },
    { key:'fontSize',   type:'number',  label:'Font Size',    def:11, min:6, max:40 },
    { key:'fontColor',  type:'color',   label:'Font Color',   def:'#0F4C81' },
    { key:'bold',       type:'boolean', label:'Bold',         def:true },
    { key:'backColor',  type:'color',   label:'Background',   def:'#E8F0F7' },
    { key:'outline',    type:'enum',    label:'Outline',      def:'Top', options:['None','Frame','Top','Bottom','Left','Right','TopBottom'] },
    { key:'outlineColor',type:'color',  label:'Outline Color',def:'#0F4C81' },
  ],
  gauge: [
    { key:'arcAngle',         type:'number',  label:'Arc Angle',         def:150, min:60, max:270 },
    { key:'startAngle',       type:'number',  label:'Start Angle',       def:-150, min:-180, max:0 },
    { key:'pinNeedle',        type:'boolean', label:'Pin Needle',        def:false },
    { key:'targetColor',      type:'color',   label:'Target Color',      def:'#E76F51' },
    { key:'foregroundColor',  type:'color',   label:'Foreground Color',  def:'#1F8AC0' },
    { key:'backgroundColor',  type:'color',   label:'Background Color',  def:'#E0E0E0' },
  ],
  dataLabels: [
    { key:'show',              type:'boolean', label:'Show Labels',      def:false },
    { key:'color',             type:'color',   label:'Color',            def:'#0F4C81' },
    { key:'fontFamily',        type:'enum',    label:'Font Family',      def:'Segoe UI', options:FONTS },
    { key:'fontSize',          type:'number',  label:'Font Size',        def:24, min:6, max:96 },
    { key:'bold',              type:'boolean', label:'Bold',             def:false },
    { key:'labelDisplayUnits', type:'enum',    label:'Display Units',    def:'0', options:['0','1000','1000000','1000000000'] },
    { key:'labelPrecision',    type:'number',  label:'Decimal Places',   def:0, min:0, max:10 },
  ],
  categoryLabels: [
    { key:'show',       type:'boolean', label:'Show Category',   def:true },
    { key:'color',      type:'color',   label:'Color',           def:'#666666' },
    { key:'fontFamily', type:'enum',    label:'Font Family',     def:'Segoe UI', options:FONTS },
    { key:'fontSize',   type:'number',  label:'Font Size',       def:12, min:6, max:40 },
    { key:'bold',       type:'boolean', label:'Bold',            def:false },
    { key:'italic',     type:'boolean', label:'Italic',          def:false },
  ],
  sentimentColors: [
    { key:'increaseFill', type:'color', label:'Increase Color', def:'#2A9D8F' },
    { key:'decreaseFill', type:'color', label:'Decrease Color', def:'#E76F51' },
    { key:'totalFill',    type:'color', label:'Total Color',    def:'#0F4C81' },
  ],
  innerRadius: [
    { key:'innerRadiusRatio', type:'number', label:'Inner Radius %', def:50, min:0, max:90 },
  ],
  bubbles: [
    { key:'minBubbleSize', type:'number', label:'Min Bubble Size', def:10, min:1, max:100 },
    { key:'maxBubbleSize', type:'number', label:'Max Bubble Size', def:40, min:1, max:200 },
  ],
  shapes: [
    { key:'strokeWidth', type:'number',  label:'Line Width',    def:2, min:1, max:10 },
    { key:'showMarker',  type:'boolean', label:'Show Markers',  def:false },
    { key:'markerSize',  type:'number',  label:'Marker Size',   def:3, min:1, max:20 },
  ],
  wordWrap: [
    { key:'show', type:'boolean', label:'Word Wrap', def:false },
  ],
  indicator: [
    { key:'show',      type:'boolean', label:'Show Indicator', def:true },
    { key:'thickness', type:'number',  label:'Thickness',      def:3, min:1, max:10 },
  ],
  trendline: [
    { key:'show',  type:'boolean', label:'Show Trendline',  def:true },
    { key:'color', type:'color',   label:'Trendline Color', def:'#1F8AC0' },
  ],
  goals: [
    { key:'show',       type:'boolean', label:'Show Goal',   def:true },
    { key:'fontFamily', type:'enum',    label:'Font Family', def:'Segoe UI', options:FONTS },
    { key:'fontSize',   type:'number',  label:'Font Size',   def:12, min:6, max:40 },
    { key:'color',      type:'color',   label:'Color',       def:'#666666' },
  ],
  statusGraphic: [
    { key:'show', type:'boolean', label:'Show Status Graphic', def:true },
  ],
  fillPoint: [
    { key:'show', type:'boolean', label:'Fill Data Points', def:true },
  ],
  fill: [
    { key:'show',         type:'boolean', label:'Show Fill',     def:true },
    { key:'fillColor',    type:'color',   label:'Fill Color',    def:'#1F8AC0' },
    { key:'transparency', type:'number',  label:'Transparency',  def:0, min:0, max:100 },
  ],
  shapeOutline: [
    { key:'show',         type:'boolean', label:'Show Outline',   def:false },
    { key:'lineColor',    type:'color',   label:'Outline Color',  def:'#0F4C81' },
    { key:'weight',       type:'number',  label:'Outline Weight', def:1, min:1, max:10 },
    { key:'transparency', type:'number',  label:'Transparency',   def:0, min:0, max:100 },
  ],
  outline: [
    { key:'show',   type:'boolean', label:'Show Outline',  def:false },
    { key:'color',  type:'color',   label:'Outline Color', def:'#E0E0E0' },
    { key:'weight', type:'number',  label:'Weight',        def:1, min:1, max:10 },
  ],
  bar: [
    { key:'show',   type:'boolean', label:'Show Bar',    def:true },
    { key:'color',  type:'color',   label:'Bar Color',   def:'#1F8AC0' },
    { key:'weight', type:'number',  label:'Bar Weight',  def:4, min:1, max:10 },
  ],
  cardTitle: [
    { key:'show',       type:'boolean', label:'Show Title',  def:true },
    { key:'fontFamily', type:'enum',    label:'Font Family', def:'Segoe UI Semibold', options:FONTS },
    { key:'fontSize',   type:'number',  label:'Font Size',   def:12, min:6, max:40 },
    { key:'color',      type:'color',   label:'Color',       def:'#0F4C81' },
  ],
  imageScaling: [
    { key:'imageScalingType', type:'enum', label:'Scaling', def:'Fit', options:['Fit','Fill','Normal'] },
  ],
  text: [
    { key:'show',              type:'boolean', label:'Show Text',          def:true },
    { key:'fontFamily',        type:'enum',    label:'Font Family',        def:'Segoe UI', options:FONTS },
    { key:'fontSize',          type:'number',  label:'Font Size',          def:12, min:6, max:96 },
    { key:'bold',              type:'boolean', label:'Bold',               def:false },
    { key:'fontColor',         type:'color',   label:'Font Color',         def:'#FFFFFF' },
    { key:'alignment',         type:'enum',    label:'H Alignment',        def:'center', options:['left','center','right'] },
    { key:'verticalAlignment', type:'enum',    label:'V Alignment',        def:'middle', options:['top','middle','bottom'] },
  ],
  zoom: [
    { key:'enableScrollWheelZoom', type:'boolean', label:'Scroll Wheel Zoom', def:true },
    { key:'show', type:'boolean', label:'Show Zoom Slider', def:false },
  ],
  annotations: [
    { key:'show', type:'boolean', label:'Show Annotations', def:true },
    { key:'color', type:'color', label:'Color', def:'#0F4C81' },
    { key:'fontSize', type:'number', label:'Font Size', def:10, min:6, max:40 },
    { key:'fontFamily', type:'enum', label:'Font Family', def:'Segoe UI', options:FONTS },
    { key:'bold', type:'boolean', label:'Bold', def:false },
    { key:'italic', type:'boolean', label:'Italic', def:false },
  ],
  forecast: [
    { key:'show', type:'boolean', label:'Show Forecast', def:false },
    { key:'lineColor', type:'color', label:'Line Color', def:'#E76F51' },
    { key:'lineWidth', type:'number', label:'Line Width', def:2, min:1, max:10 },
    { key:'lineStyle', type:'enum', label:'Line Style', def:'dashed', options:['solid','dashed','dotted'] },
    { key:'confidenceBandStyle', type:'enum', label:'Confidence Band', def:'fill', options:['fill','line','none'] },
    { key:'transparency', type:'number', label:'Transparency', def:80, min:0, max:100 },
    { key:'units', type:'enum', label:'Forecast Length', def:'auto', options:['auto','points'] },
  ],
  referenceLine: [
    { key:'show', type:'boolean', label:'Show Reference Line', def:false },
    { key:'value', type:'number', label:'Value', def:0, min:-1e9, max:1e9 },
    { key:'lineColor', type:'color', label:'Line Color', def:'#E76F51' },
    { key:'lineWidth', type:'number', label:'Line Width', def:1, min:1, max:10 },
    { key:'lineStyle', type:'enum', label:'Line Style', def:'dashed', options:['solid','dashed','dotted'] },
    { key:'transparency', type:'number', label:'Transparency', def:0, min:0, max:100 },
    { key:'labelShow', type:'boolean', label:'Show Label', def:true },
    { key:'labelColor', type:'color', label:'Label Color', def:'#444444' },
    { key:'labelPosition', type:'enum', label:'Label Position', def:'Above', options:['Above','Below','Left','Right'] },
  ],
  markers: [
    { key:'show', type:'boolean', label:'Show Markers', def:false },
    { key:'markerSize', type:'number', label:'Size', def:5, min:1, max:20 },
    { key:'markerShape', type:'enum', label:'Shape', def:'circle', options:['circle','square','diamond','triangle','x','cross'] },
    { key:'markerColor', type:'color', label:'Color', def:'#0F4C81' },
  ],
  smallMultiplesLayout: [
    { key:'numRows', type:'number', label:'Rows', def:2, min:1, max:20 },
    { key:'numColumns', type:'number', label:'Columns', def:2, min:1, max:20 },
    { key:'borderColor', type:'color', label:'Border Color', def:'#E0E0E0' },
    { key:'borderWidth', type:'number', label:'Border Width', def:1, min:0, max:10 },
    { key:'showPanelBorder', type:'boolean', label:'Show Panel Border', def:true },
    { key:'showSeparator', type:'boolean', label:'Show Separator', def:true },
    { key:'individualSlicerTitle', type:'boolean', label:'Individual Title', def:true },
    { key:'panelTitleFontSize', type:'number', label:'Panel Title Size', def:11, min:6, max:40 },
    { key:'panelTitleColor', type:'color', label:'Panel Title Color', def:'#333333' },
    { key:'panelTitleFontFamily', type:'enum', label:'Panel Title Font', def:'Segoe UI', options:FONTS },
  ],
  seriesLabels: [
    { key:'show', type:'boolean', label:'Show Series Labels', def:false },
    { key:'color', type:'color', label:'Color', def:'#444444' },
    { key:'fontSize', type:'number', label:'Font Size', def:9, min:6, max:40 },
    { key:'fontFamily', type:'enum', label:'Font Family', def:'Segoe UI', options:FONTS },
    { key:'bold', type:'boolean', label:'Bold', def:false },
    { key:'italic', type:'boolean', label:'Italic', def:false },
  ],
  searchBox: [
    { key:'show', type:'boolean', label:'Show Search', def:false },
    { key:'color', type:'color', label:'Text Color', def:'#333333' },
    { key:'background', type:'color', label:'Background', def:'#FFFFFF' },
    { key:'border', type:'color', label:'Border Color', def:'#E0E0E0' },
  ],
  slicerHeader: [
    { key:'show',       type:'boolean', label:'Show Header',  def:true },
    { key:'fontFamily', type:'enum',    label:'Font Family',  def:'Segoe UI Semibold', options:FONTS },
    { key:'textSize',   type:'number',  label:'Font Size',    def:12, min:6, max:40 },
    { key:'fontColor',  type:'color',   label:'Font Color',   def:'#0F4C81' },
    { key:'bold',       type:'boolean', label:'Bold',         def:true },
    { key:'italic',     type:'boolean', label:'Italic',       def:false },
    { key:'underline',  type:'boolean', label:'Underline',    def:false },
    { key:'background', type:'color',   label:'Background',   def:'#FFFFFF' },
    { key:'outline',    type:'enum',    label:'Outline',      def:'None', options:['None','Frame','Top','Bottom','Left','Right','TopBottom'] },
  ],
  slicerItems: [
    { key:'fontFamily', type:'enum',    label:'Font Family',  def:'Segoe UI', options:FONTS },
    { key:'textSize',   type:'number',  label:'Font Size',    def:11, min:6, max:40 },
    { key:'fontColor',  type:'color',   label:'Font Color',   def:'#333333' },
    { key:'bold',       type:'boolean', label:'Bold',         def:false },
    { key:'italic',     type:'boolean', label:'Italic',       def:false },
    { key:'background', type:'color',   label:'Background',   def:'#FFFFFF' },
    { key:'outline',    type:'enum',    label:'Outline Style',def:'Frame', options:['None','Frame','Top','Bottom','Left','Right','TopBottom'] },
    { key:'padding',    type:'number',  label:'Padding',      def:3, min:0, max:20 },
  ],
  slider: [
    { key:'color', type:'color', label:'Slider Color', def:'#1F8AC0' },
    { key:'textSize', type:'number', label:'Text Size', def:11, min:6, max:40 },
  ],
  sparklines: [
    { key:'show', type:'boolean', label:'Show Sparklines', def:false },
    { key:'lineColor', type:'color', label:'Line Color', def:'#1F8AC0' },
    { key:'lineWidth', type:'number', label:'Line Width', def:1, min:1, max:5 },
    { key:'markerShow', type:'boolean', label:'Show Markers', def:false },
    { key:'markerColor', type:'color', label:'Marker Color', def:'#0F4C81' },
    { key:'type', type:'enum', label:'Type', def:'line', options:['line','bar'] },
  ],
  columnFormatting: [
    { key:'urlIcon', type:'boolean', label:'Show URL Icon', def:false },
    { key:'urlNewTab', type:'boolean', label:'Open in New Tab', def:true },
    { key:'wordWrap', type:'boolean', label:'Word Wrap', def:false },
  ],
  accessibility: [
    { key:'show', type:'boolean', label:'Show Accessibility', def:true },
  ],
  colorByCategory: [
    { key:'show', type:'boolean', label:'Color by Category', def:false },
  ],
  clustering: [
    { key:'show', type:'boolean', label:'Show Clusters', def:false },
    { key:'numClusters', type:'number', label:'Number of Clusters', def:5, min:2, max:20 },
  ],
  plotAreaShading: [
    { key:'show', type:'boolean', label:'Show Shading', def:false },
    { key:'color', type:'color', label:'Shading Color', def:'#E0E0E0' },
    { key:'transparency', type:'number', label:'Transparency', def:60, min:0, max:100 },
  ],
  y2Axis: [
    { key:'show', type:'boolean', label:'Show Secondary Axis', def:false },
    { key:'labelColor', type:'color', label:'Label Color', def:'#666666' },
    { key:'fontFamily', type:'enum', label:'Font Family', def:'Segoe UI', options:FONTS },
    { key:'fontSize', type:'number', label:'Font Size', def:11, min:6, max:40 },
    { key:'showAxisTitle', type:'boolean', label:'Show Title', def:false },
    { key:'gridlineShow', type:'boolean', label:'Show Gridlines', def:false },
    { key:'gridlineColor', type:'color', label:'Gridline Color', def:'#E0E0E0' },
  ],
  scorecard: [
    { key:'fontFamily', type:'enum', label:'Font Family', def:'Segoe UI', options:FONTS },
    { key:'fontSize', type:'number', label:'Font Size', def:12, min:6, max:40 },
    { key:'fontColor', type:'color', label:'Font Color', def:'#333333' },
    { key:'background', type:'color', label:'Background', def:'#FFFFFF' },
    { key:'showGoalBadges', type:'boolean', label:'Show Goal Badges', def:true },
    { key:'showOwner', type:'boolean', label:'Show Owner', def:false },
    { key:'showDueDate', type:'boolean', label:'Show Due Date', def:false },
  ],
  cardVisualSettings: [
    { key:'show', type:'boolean', label:'Show', def:true },
    { key:'fontFamily', type:'enum', label:'Font Family', def:'Segoe UI Light', options:FONTS },
    { key:'fontSize', type:'number', label:'Font Size', def:32, min:6, max:96 },
    { key:'fontColor', type:'color', label:'Font Color', def:'#0F4C81' },
    { key:'bold', type:'boolean', label:'Bold', def:false },
    { key:'italic', type:'boolean', label:'Italic', def:false },
    { key:'alignment', type:'enum', label:'Alignment', def:'center', options:['left','center','right'] },
    { key:'labelDisplayUnits', type:'enum', label:'Display Units', def:'0', options:['0','1000','1000000','1000000000'] },
    { key:'labelPrecision', type:'number', label:'Decimal Places', def:0, min:0, max:10 },
  ],
  data: [
    { key:'mode',       type:'enum',   label:'Slicer Mode',  def:'VerticalList', options:['VerticalList','HorizontalList','Dropdown','Between','Before','After','Basic','Relative','RelativeTime','Single'] },
    { key:'fontFamily', type:'enum',   label:'Font Family', def:'Segoe UI', options:FONTS },
    { key:'fontSize',   type:'number', label:'Font Size',   def:12, min:6, max:40 },
    { key:'fontColor',  type:'color',  label:'Font Color',  def:'#333333' },
    { key:'bold',       type:'boolean',label:'Bold',        def:false },
    { key:'italic',     type:'boolean',label:'Italic',      def:false },
  ],
  detail: [
    { key:'show', type:'boolean', label:'Show Detail', def:false },
  ],
  target: [
    { key:'show',       type:'boolean', label:'Show Target',  def:true },
    { key:'fontFamily', type:'enum',    label:'Font Family',  def:'Segoe UI', options:FONTS },
    { key:'fontSize',   type:'number',  label:'Font Size',    def:12, min:6, max:40 },
    { key:'color',      type:'color',   label:'Color',        def:'#666666' },
  ],
  pageSize: [
    { key:'type', type:'enum', label:'Format', def:'Custom', options:['Custom','16:9 (HD 1280×720)','16:9 (Full HD 1920×1080)','16:9 (4K 3840×2160)','4:3 (960×720)','Letter (816×1056)','A4 (793×1122)','Mobile Portrait (320×568)','Square (700×700)'] },
    { key:'width', type:'number', label:'Width (px)', def:1280, min:200, max:5000 },
    { key:'height', type:'number', label:'Height (px)', def:720, min:200, max:5000 },
  ],
  pageBackground: [
    { key:'color', type:'color', label:'Background Color', def:'#FFFFFF' },
    { key:'transparency', type:'number', label:'Transparency (%)', def:0, min:0, max:100 },
    { key:'image', type:'string', label:'Background Image URL', def:'' },
    { key:'imageFit', type:'enum', label:'Image Fit', def:'Normal', options:['Normal','Fit','Fill','Tile'] },
  ],
  pageWallpaper: [
    { key:'color', type:'color', label:'Wallpaper Color', def:'#F2F2F2' },
    { key:'transparency', type:'number', label:'Transparency (%)', def:0, min:0, max:100 },
    { key:'image', type:'string', label:'Wallpaper Image URL', def:'' },
    { key:'imageFit', type:'enum', label:'Image Fit', def:'Fill', options:['Normal','Fit','Fill','Tile'] },
  ],
  filterPane: [
    { key:'backgroundColor', type:'color', label:'Background Color', def:'#F2F2F2' },
    { key:'foregroundColor', type:'color', label:'Header Color', def:'#000000' },
    { key:'fontFamily', type:'enum', label:'Font Family', def:'Segoe UI', options:FONTS },
    { key:'fontSize', type:'number', label:'Font Size', def:12, min:6, max:40 },
    { key:'borderColor', type:'color', label:'Border Color', def:'#E0E0E0' },
    { key:'fieldTitleColor', type:'color', label:'Filter Title Color', def:'#000000' },
    { key:'fieldSearchColor', type:'color', label:'Search Color', def:'#333333' },
    { key:'applyButtonColor', type:'color', label:'Apply Button Color', def:'#0F4C81' },
  ],
};

export const VISUAL_SCHEMA = {
  '*':                            ['general','title','subheader','background','border','shadow'],
  barChart:                       ['general','title','subheader','legend','categoryAxis','valueAxis','labels','dataPoint','plotArea','trend','zoom'],
  clusteredBarChart:              ['general','title','subheader','legend','categoryAxis','valueAxis','labels','dataPoint','plotArea','trend','zoom'],
  stackedBarChart:                ['general','title','subheader','legend','categoryAxis','valueAxis','labels','dataPoint','plotArea','zoom'],
  hundredPercentStackedBarChart:  ['general','title','subheader','legend','categoryAxis','valueAxis','labels','dataPoint','plotArea','zoom'],
  columnChart:                    ['general','title','subheader','legend','categoryAxis','valueAxis','labels','dataPoint','plotArea','trend','zoom'],
  clusteredColumnChart:           ['general','title','subheader','legend','categoryAxis','valueAxis','labels','dataPoint','plotArea','trend','zoom'],
  stackedColumnChart:             ['general','title','subheader','legend','categoryAxis','valueAxis','labels','dataPoint','plotArea','zoom'],
  hundredPercentStackedColumnChart:['general','title','subheader','legend','categoryAxis','valueAxis','labels','dataPoint','plotArea','zoom'],
  lineChart:                      ['general','title','subheader','legend','categoryAxis','valueAxis','labels','dataPoint','lineStyles','markers','plotArea','trend','forecast','referenceLine','annotations','smallMultiplesLayout','seriesLabels','zoom'],
  areaChart:                      ['general','title','subheader','legend','categoryAxis','valueAxis','labels','dataPoint','markers','plotArea','trend','referenceLine','annotations','smallMultiplesLayout','zoom'],
  stackedAreaChart:               ['general','title','subheader','legend','categoryAxis','valueAxis','labels','dataPoint','plotArea','annotations','smallMultiplesLayout','zoom'],
  ribbonChart:                    ['general','title','subheader','legend','categoryAxis','valueAxis','labels','dataPoint','plotArea'],
  waterfallChart:                 ['general','title','subheader','legend','categoryAxis','valueAxis','labels','sentimentColors','plotArea','zoom'],
  scatterChart:                   ['general','title','subheader','legend','categoryAxis','valueAxis','labels','dataPoint','fillPoint','markers','plotArea','trend','referenceLine','clustering','colorByCategory','plotAreaShading','zoom'],
  pieChart:                       ['general','title','subheader','legend','labels','dataPoint','detail'],
  donutChart:                     ['general','title','subheader','legend','labels','dataPoint','innerRadius','detail'],
  treemap:                        ['general','title','subheader','legend','labels','categoryLabels','dataPoint'],
  funnel:                         ['general','title','subheader','legend','labels','dataPoint'],
  gauge:                          ['general','title','subheader','dataLabels','gauge','target'],
  card:                           ['general','title','dataLabels','categoryLabels','wordWrap','background','border'],
  multiRowCard:                   ['general','title','dataLabels','categoryLabels','cardTitle','outline','bar','background','border'],
  kpi:                            ['general','title','indicator','trendline','dataLabels','goals','statusGraphic'],
  slicer:                         ['general','title','slicerHeader','slicerItems','selection','data','searchBox','slider','background','border'],
  tableEx:                        ['general','title','grid','columnHeaders','values','total','sparklines','columnFormatting','accessibility','background','border'],
  matrix:                         ['general','title','grid','rowHeaders','columnHeaders','values','subTotals','sparklines','columnFormatting','accessibility','background','border'],
  lineClusteredColumnComboChart:  ['general','title','subheader','legend','categoryAxis','valueAxis','y2Axis','labels','dataPoint','lineStyles','markers','plotArea','trend','referenceLine','annotations','zoom'],
  lineStackedColumnComboChart:    ['general','title','subheader','legend','categoryAxis','valueAxis','y2Axis','labels','dataPoint','lineStyles','markers','plotArea','trend','referenceLine','annotations','zoom'],
  decompositionTree:              ['general','title','subheader','legend','labels','dataLabels','header'],
  hundredPercentStackedAreaChart: ['general','title','subheader','legend','categoryAxis','valueAxis','labels','dataPoint','plotArea','zoom'],
  advancedSlicerVisual:           ['general','title','slicerHeader','slicerItems','selection','searchBox','background','border'],
  listSlicer:                     ['general','title','slicerHeader','slicerItems','selection','searchBox','background','border'],
  pivotTable:                     ['general','title','grid','rowHeaders','columnHeaders','values','subTotals','sparklines','accessibility','background','border'],
  scorecard:                      ['general','title','scorecard','background','border'],
  cardVisual:                     ['general','title','cardVisualSettings','categoryLabels','background','border'],
  bookmarkNavigator:              ['general','title','text','fill','outline','shadow','border'],
  pageNavigator:                  ['general','title','text','fill','outline','shadow','border'],
  azureMap:                       ['general','title','legend','dataPoint','bubbles','background','border'],
  shape:                          ['general','title','fill','shapeOutline','background','border'],
  textbox:                        ['background','border','shadow'],
  actionButton:                   ['text','fill','outline','shadow','border'],
  __page__:                       ['pageSize','pageBackground','pageWallpaper','filterPane'],
};
