export const VISUAL_LABELS = {
  '*':                             'Global (All Visuals)',
  'barChart':                      'Bar Chart',
  'clusteredBarChart':             'Clustered Bar Chart',
  'stackedBarChart':               'Stacked Bar Chart',
  'hundredPercentStackedBarChart': '100% Stacked Bar Chart',
  'columnChart':                   'Column Chart',
  'clusteredColumnChart':          'Clustered Column Chart',
  'stackedColumnChart':            'Stacked Column Chart',
  'hundredPercentStackedColumnChart': '100% Stacked Column Chart',
  'lineChart':                     'Line Chart',
  'areaChart':                     'Area Chart',
  'stackedAreaChart':              'Stacked Area Chart',
  'hundredPercentStackedAreaChart': '100% Stacked Area Chart',
  'lineClusteredColumnComboChart': 'Line & Clustered Column Combo',
  'lineStackedColumnComboChart':   'Line & Stacked Column Combo',
  'ribbonChart':                   'Ribbon Chart',
  'waterfallChart':                'Waterfall Chart',
  'scatterChart':                  'Scatter Chart',
  'funnel':                        'Funnel',
  'pieChart':                      'Pie Chart',
  'donutChart':                    'Donut Chart',
  'treemap':                       'Treemap',
  'azureMap':                      'Azure Maps',
  'card':                          'Card',
  'cardVisual':                    'Card (New)',
  'multiRowCard':                  'Multi-Row Card',
  'kpi':                           'KPI',
  'gauge':                         'Gauge',
  'scorecard':                     'Scorecard',
  'tableEx':                       'Table',
  'matrix':                        'Matrix',
  'pivotTable':                    'Pivot Table',
  'slicer':                        'Slicer',
  'advancedSlicerVisual':          'Advanced Slicer',
  'listSlicer':                    'List Slicer',
  'decompositionTree':             'Decomposition Tree',
  'bookmarkNavigator':             'Bookmark Navigator',
  'pageNavigator':                 'Page Navigator',
  'actionButton':                  'Button',
  'textbox':                       'Text Box',
  'shape':                         'Shape',
};

export const VISUAL_CATEGORIES = {
  'Bar Charts': ['barChart', 'clusteredBarChart', 'stackedBarChart', 'hundredPercentStackedBarChart'],
  'Column Charts': ['columnChart', 'clusteredColumnChart', 'stackedColumnChart', 'hundredPercentStackedColumnChart'],
  'Line & Area': ['lineChart', 'areaChart', 'stackedAreaChart', 'hundredPercentStackedAreaChart'],
  'Combo Charts': ['lineClusteredColumnComboChart', 'lineStackedColumnComboChart', 'ribbonChart'],
  'Other Cartesian': ['waterfallChart', 'scatterChart', 'funnel'],
  'Pie / Donut / Tree': ['pieChart', 'donutChart', 'treemap'],
  'Maps': ['azureMap'],
  'Cards & KPI': ['card', 'cardVisual', 'multiRowCard', 'kpi', 'gauge', 'scorecard'],
  'Tables': ['tableEx', 'matrix', 'pivotTable'],
  'Slicers': ['slicer', 'advancedSlicerVisual', 'listSlicer'],
  'AI / Analytics': ['decompositionTree'],
  'Navigation & Buttons': ['bookmarkNavigator', 'pageNavigator', 'actionButton'],
  'Static Elements': ['textbox', 'shape'],
};

export const CARD_NAME_MAP = {
  general: 'General', title: 'Title', subheader: 'Subtitle', legend: 'Legend',
  categoryAxis: 'Category Axis', valueAxis: 'Value Axis', y2Axis: 'Secondary Axis',
  labels: 'Data Labels', dataPoint: 'Data Point', plotArea: 'Plot Area',
  trend: 'Trend Line', zoom: 'Zoom', lineStyles: 'Line Style', markers: 'Markers',
  referenceLine: 'Reference Line', annotations: 'Annotations', forecast: 'Forecast',
  smallMultiplesLayout: 'Small Multiples', seriesLabels: 'Series Labels',
  detail: 'Detail', innerRadius: 'Inner Radius', fillPoint: 'Fill Point',
  clustering: 'Clustering', colorByCategory: 'Color by Category',
  plotAreaShading: 'Plot Area Shading', sentimentColors: 'Sentiment Colors',
  wordWrap: 'Word Wrap', shapes: 'Shapes', gauge: 'Gauge', target: 'Target',
  data: 'Data', selection: 'Selection', header: 'Header', items: 'Items',
  grid: 'Grid', columnHeaders: 'Column Headers', values: 'Values', total: 'Total',
  rowHeaders: 'Row Headers', subtotals: 'Subtotals', bubbles: 'Bubbles',
  cardTitle: 'Card Title', shapeOutline: 'Outline', slicerHeader: 'Header', slicerItems: 'Items',
  indicator: 'Indicator', trendline: 'Trend Line',
  goals: 'Goals', statusGraphic: 'Status Indicator', fill: 'Fill', line: 'Line',
  outline: 'Outline', shadow: 'Shadow', border: 'Border', background: 'Background',
  text: 'Text', y2AxisReferenceLine: 'Secondary Axis Reference Line',
  cardVisualSettings: 'Card Value', categoryLabels: 'Category Label',
  dataLabels: 'Data Labels', subTotals: 'Subtotals',
  searchBox: 'Search', slider: 'Slider', sparklines: 'Sparklines',
  columnFormatting: 'Column Formatting', accessibility: 'Accessibility',
  scorecard: 'Scorecard', pageSize: 'Page Size', pageBackground: 'Page Background',
  pageWallpaper: 'Wallpaper', filterPane: 'Filter Pane',
};
